SUMMARY.md, docs/sdk/api/README.md, docs/sdk/api/createUserAgentMiddleware.md, integration-tests/package.json, integration-tests/sdk/channels.it.js, packages/commercetools-sdk-middleware-user-agent/README.md, packages/commercetools-sdk-middleware-user-agent/package.json, packages/commercetools-sdk-middleware-user-agent/src/create-user-agent.js, packages/commercetools-sdk-middleware-user-agent/src/index.js, packages/commercetools-sdk-middleware-user-agent/src/user-agent.js, packages/commercetools-sdk-middleware-user-agent/test/create-user-agent.spec.js, packages/commercetools-sdk-middleware-user-agent/test/user-agent.spec.js, types/sdk.js
Add a middleware to properly provide `User-Agent` for HTTP requests, following spec.
```js
import { createClient } from '@commercetools/sdk-client'
import { createUserAgentMiddleware } from '@commercetools/sdk-middleware-user-agent'
import { createAuthMiddleware } from '@commercetools/sdk-middleware-auth'
import { createHttpMiddleware } from '@commercetools/sdk-middleware-http'
const userAgentMiddleware = createUserAgentMiddleware(),
const client = createClient({
middlewares: [
createAuthMiddleware({...}),
createUserAgentMiddleware({
name: 'my-awesome-library',
version: '1.0.0',
url: 'https://github.com/my-company/my-awesome-library'
}),
createHttpMiddleware({...}),
],
})
// The User-Agent will be for example:
// commercetools-node-sdk Node.js/6.9.0 (darwin; x64) my-awesome-library/1.0.0 …
```
=> Add middleware to define the user-agent for http requests

docs/sdk/api/createClient.md, integration-tests/sdk/channels.it.js, packages/commercetools-sdk-client/src/client.js, packages/commercetools-sdk-client/test/client.spec.js, types/sdk.js
Implements the `process` function to be able to iterate through all the pages of a HTTP endpoint.
```js
import { createClient } from '@commercetools/sdk-client'
import { createHttpMiddleware } from '@commercetools/sdk-middleware-http'
import { createRequestBuilder } from '@commercetools/api-request-builder'
const requestBuilder = createRequestBuilder()
const productProjectionsService = requestBuilder.productProjections
const productsService = requestBuilder.products
const client = createClient({
middlewares: [
createHttpMiddleware(),
],
})
const uri = productProjectionsService
.where('masterData(published = "false")')
.where('masterData(hasStagedChanges = "true")')
.build({ projectKey: 'foo' })
const request = {
uri,
method: 'GET',
headers: {
Authorization: 'Bearer xxx',
},
}
// 1. We …
```
=> feat(sdk-client): implement process function to iterate through pages

packages/commercetools-api-request-builder/src/default-services.js, packages/commercetools-api-request-builder/test/create-request-builder.spec.js
affects: @commercetools/api-request-builder
- Tests
=> feat(api-request-builder): add the types service

packages/commercetools-sync-actions/package.json, packages/commercetools-sync-actions/src/utils/diffpatcher.js
Upgrade back to official version of `jsondiffpatch` and use import workaround to make it work in webpack
=> refactor(sync-actions): upgrade jsondiffpatch and properly import it

.travis.yml, .travis/scripts.sh
- builds now will fail fast if an error occurs `set -e`
- don't run *it* tests if PR is coming from a fork (Closes #30)
=> build(travis): fail fast and avoid running it tests for PRs coming from forks

packages/commercetools-api-request-builder/src/create-service.js, packages/commercetools-api-request-builder/src/default-services.js, packages/commercetools-api-request-builder/src/query-id.js, packages/commercetools-api-request-builder/src/query-projection.js, packages/commercetools-api-request-builder/test/create-request-builder.spec.js, packages/commercetools-api-request-builder/test/create-service.spec.js, packages/commercetools-api-request-builder/test/query-id.spec.js, packages/commercetools-sdk-client/src/client.js, packages/commercetools-sdk-middleware-http/src/http.js, packages/commercetools-sdk-middleware-logger/src/logger.js, packages/commercetools-sync-actions/src/product-actions.js
Define remaining services for API endpoints.
Note: there are a few extra things that should also be supported but they can be done separately.
- Tests
=> feat(api-request-builder): add missing services to cover all API endpoints

.gitignore, CHANGELOG.md, lerna.json
Add initial historical changelog, using `lerna-changelog`.
> Note: I've created it using the new version of `lerna-changelog` [with some new features](https://github.com/lerna/lerna-changelog/pull/31). When it will be merged / released I'll add also the dependency, until then please ask me if you want to do something with it.
=> Generate changelog for published packages

packages/commercetools-sdk-middleware-auth/src/build-requests.js, packages/commercetools-sdk-middleware-auth/src/client-credentials-flow.js, packages/commercetools-sdk-middleware-auth/test/build-requests.spec.js, packages/commercetools-sdk-middleware-auth/test/client-crendentials-flow.spec.js
BREAKING CHANGE: `host` is now a required option, no more default value
Yesterday I realized that the usage of the token cache was not properly done (new token would be retrieved for each new request).
Additionally, after some conversation yesterday, we should not put any _default_ `host` values, as our platform as already multiple data centers. It also keeps the middleware more decoupled from our platform. 
- Tests
=> fix(middleware-auth): fix usage of cached token, no default options

packages/commercetools-sdk-middleware-http/src/http.js, packages/commercetools-sdk-middleware-http/test/http.spec.js
BREAKING CHANGE: `host` is now a required option, no more default value
Follow discussion in #53
=> refactor(middleware-http): make host option required

docs/sdk/Glossary.md, docs/sdk/README.md, docs/sdk/Testing.md, docs/sdk/api/sdkMiddlewareAuth.md, docs/sdk/api/sdkMiddlewareHttp.md, docs/sdk/upgrading-from-sphere-node-sdk.md, packages/commercetools-sdk-client/src/client.js, packages/commercetools-sdk-client/test/client.spec.js, packages/commercetools-sdk-middleware-auth/src/client-credentials-flow.js, packages/commercetools-sdk-middleware-http/src/http.js, packages/commercetools-sdk-middleware-http/test/http.spec.js, packages/commercetools-sdk-middleware-logger/src/logger.js, packages/commercetools-sdk-middleware-queue/src/queue.js, packages/commercetools-sdk-middleware-user-agent/src/user-agent.js, types/sdk.js
Add `MiddlewareRequest` and `MiddlewareResponse` types, which are slightly different from `ClientRequest` and `ClientResponse`. This is to avoid some confusions around some return types.
=> refactor(sdk): use more specific types for middlewares args

package.json, packages/commercetools-http-user-agent/src/create-user-agent.js, packages/commercetools-http-user-agent/test/create-user-agent.spec.js, packages/commercetools-sdk-middleware-auth/src/build-requests.js, packages/commercetools-sdk-middleware-auth/src/client-credentials-flow.js, packages/commercetools-sdk-middleware-auth/test/build-requests.spec.js, scripts/test-package, test-config.json
Fixes #46
This PR fixes the problem in `node` environment caused by `global.window`.
For `auth`, since we were using `Buffer` anyway, we can simply use the polyfill provided by webpack.
For `user-agent` it's fixed (see comment) in a different way, but allows to easily test it.
Additionally, I realised that running the tests scoped by package didn't use the jest config defined in `package.json` (because of the directory context), so I've put the config into a `test-config.json` file and each script running `jest` will reference to the file config.
And tests run in `node` environment now by default (jest uses `jsdom` by default).
=> Safely check for browser env when accessing global.window

integration-tests/cli/csv-parser-price.it.js, packages/csv-parser-price/package.json
The `api-request-builder` package [has been bumped](https://github.com/commercetools/nodejs/commit/3bed0bd3db3e9674d39ea5e32643ec4bd0203135) but the version has not been updated here.
I think we should start doing the publishing manually, using `lerna publish`.
=> chore(package): update api-request-builder version

packages/sdk-middleware-auth/src/build-requests.js, packages/sdk-middleware-auth/test/build-requests.spec.js, types/sdk.js
Allow to pass a custom `oauthUri`, mostly useful for internal usage.
- Tests
=> feat(sdk-middleware-auth): allow to pass custom uri

packages/api-request-builder/src/default-services.js, packages/api-request-builder/test/create-request-builder.spec.js
Resolves #132 
This PR adds a project endpoint to the list of default endpoints so it can be used on Impex.
- Tests
=> feat(apiRequestBuilder): Add a support for project endpoint

packages/sync-actions/package.json, packages/sync-actions/src/utils/common-actions.js, packages/sync-actions/test/utils/common-actions.spec.js
This will fix https://github.com/commercetools/nodejs/issues/145
At the moment, if you try to add/change a inventory quantity with number "0" the API returns a bad request error
This is happening because 0 is falsy, and on the buildBaseAttributesActions function it relies only on the value in order to define what to return
I have added a variable to check the existence of the value (`hasNow` and `hasBefore`), so 0 wouldn't return false in this case.
- Tests
=> User can't add/change inventory quantity to 0

packages/discount-code-generator/package.json, packages/discount-code-generator/src/main.js, packages/discount-code-generator/test/main.spec.js, types/discountCodes.js, types/sdk.js
affects: @commercetools/discount-code-generator
Implement the discount code generator function as part of [this](https://github.com/commercetools/nodejs/issues/142#issue-224808585) checklist
=> feat(discount-codes): implement function to generate codes

packages/sync-actions/src/product-actions.js, packages/sync-actions/test/product-sync-base.spec.js
The product key can be set using the setKey action. The API has support the SDK so far not.
The product key will be used to better support to uniquely identify a product in the merchant center.
- Tests
=> feat(product): add product key to supported actions

packages/sync-actions/src/product-actions.js, packages/sync-actions/test/product-sync-variants.spec.js
The API supports a key and sku field for product variants. The sku field is supported as an action
on the sync actions they key field not so far.
Adds the setProductVariantKey action to be supported on the master variant as any other variant.
- Tests
=> feat(product/variants): add support for key field on variants

integration-tests/cli/discount-code-importer.it.js, integration-tests/cli/inventories-exporter.it.js, package.json, packages/inventories-exporter/src/main.js, packages/inventories-exporter/test/main.spec.js
Fixes #246 
Inventories importer expects custom fields to be prefixed with `customField` name not just `custom`.
- Tests
=> fix(inventories-exporter): Change custom field prefix name

packages/api-request-builder/README.md
The old endpoint didn't work anymore.
=> fix(api-request-builder): update link to the docs

CONTRIBUTING.md, integration-tests/cli/csv-parser-price.it.js, integration-tests/cli/discount-codes.it.js, integration-tests/cli/inventories-exporter.it.js
Add separate project for each int test to avoid race conditions in CI
update contributing to run
int tests in sequence on user machine with the same project
resolves #265
=> chore(integration-tests): add separate project for each int test

docs/sdk/api/sdkMiddlewareAuth.md, integration-tests/sdk/customer-login.it.js, packages/sdk-middleware-auth/src/base-auth-flow.js, packages/sdk-middleware-auth/src/build-requests.js, packages/sdk-middleware-auth/src/client-credentials-flow.js, packages/sdk-middleware-auth/src/password-flow.js, packages/sdk-middleware-auth/src/utils.js, packages/sdk-middleware-auth/test/base-auth-flow.spec.js, packages/sdk-middleware-auth/test/build-requests.spec.js, packages/sdk-middleware-auth/test/client-crendentials-flow.spec.js, packages/sdk-middleware-auth/test/password-flow.spec.js, types/sdk.js
=> 212 password flow

docs/sdk/api/sdkClient.md, packages/sdk-client/src/client.js, packages/sdk-client/test/client.spec.js, types/sdk.js
BREAKING CHANGES: Calling `process` with a limit query now returns the `limit` number of items total and not the `limit` amount for **_"n"_** requests
resolves #294
=> feat(sdk-client): limit returned items with processFn

packages/sync-actions/src/product-actions.js, packages/sync-actions/test/product-sync-base.spec.js, packages/sync-actions/test/utils/common-actions.spec.js
This pull requests adds state transitions on products to the `sync-actions` package.
A product can have a state assigned. A state is a reference to a defined state machine. The state itself is a reference type (http://dev.commercetools.com/http-api-projects-products.html#product). When transitioning a state the API offers the `transitionState` update action http://dev.commercetools.com/http-api-projects-products.html#transition-state.
- Tests
=> feat(sync-actions): add transitionsState action on products

packages/sync-actions/src/utils/common-actions.js, packages/sync-actions/test/utils/common-actions.spec.js
Actions based on references only need to send a reference of `typeId` and `id` in addition with the reference itself. Before `sync-actions`, whenever `now` contained the expanded object would also attach those to the action. 
```json
[{
"action": "transitionState",
"state": {
"typeId": "state",
"id": "fb77d7dc-94c5-45df-95bc-b8499286e4d5",
"obj": {
"id": "fb77d7dc-94c5-45df-95bc-b8499286e4d5",
"version": 2,
"key": "new",
"type": "ProductState",
"roles": [],
"name": {
"de": "Neu",
"en": "New"
},
"builtIn": false,
"transitions": [{
"typeId": "state",
"id": "1436898f-6080-4a18-99df-134e05a80f73"
}],
"initial": true,
"createdAt": "2016-08-11T16:07:33.676Z",
"lastModifiedAt": "2016-08-11T16:07:34.888Z"
}
}
}]
```
Whereas the update action should be
```json
[{
"action": "transitionState", …
```
=> fix(sync-action): to only pass reference for reference actions

.travis/after_success.sh
Currently we fail to release as `buffer-shims` is not installed as a dependency. Before we migrated to only use `npm` but that does not seem to be a sane approach when dealing with a monorepo and opting out of `yarns` workspace support.
To be fair: we don't know why this dependency it not installed correctly and it must be a problem somewhere downstream.
Link to a borked release: https://travis-ci.org/commercetools/nodejs/jobs/301317444#L708
```bash
Running npm run semantic-release
module.js:471
throw err;
^
Error: Cannot find module 'buffer-shims'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> …
```
=> chore(travis): add manual install of buffer-shims

packages/sync-actions/src/cart-discounts-actions.js, packages/sync-actions/test/cart-discounts-sync.spec.js
Adds the `stackingMode` to cart discounts in the `sync-actions` package. This pull request closes #358.
=> Add `stackingMode` to cart discounts in sync-actions

packages/api-request-builder/src/default-params.js
Include the `whereOperator` as known key in the corresponding `knownKeys` array.
When passing the `whereOperator` as param we were getting the following error:
Basically the `whereOperator` key is not in the `knownKeys`array making it useless. This PR just fixes that by adding the operator in the array.
=> fix(api-request-builder): adds the whereOperator to the knownKeys array

docs/sdk/api/apiRequestBuilder.md, packages/api-request-builder/src/build-query-string.js, packages/api-request-builder/src/default-params.js, packages/api-request-builder/src/query-id.js, packages/api-request-builder/test/create-service.spec.js, packages/api-request-builder/test/query-id.spec.js, types/sdk.js
adds the `cartId` param as a valid one to filter like we already have with `customerId` in the `queryOne` feature.
we can call the `shipping-method` endpoint by passing a `cartId` param with the cart id in order to get the available shipping methods for the cart. See [here](https://dev.commercetools.com/http-api-projects-shippingMethods.html#get-shippingmethods-for-a-cart) the docs.
This PR adds the possibility to send as param a `cartId` in order to be able to use this feature when retrieving shipping methods.
- Tests
=> feat(query-id): add ability to filter by cart id

packages/sync-actions/src/discount-codes-actions.js, packages/sync-actions/test/discount-codes-sync.spec.js
⚠️  Please do not merge yet until this feature is available in the platform ⚠️ 
Closes #376
=> feat(sync-actions/discount-codes): add validFrom and validUntil

docs/sdk/Glossary.md, docs/sdk/api/README.md, docs/sdk/api/syncActions.md, types/sdk.js
This PR fixes an incorrect order or `buildActions` method arguments in docs.
Fixes #365
=> docs(sync-action): Correct arguments in buildActions method

packages/sync-actions/src/product-discounts-actions.js, packages/sync-actions/test/product-discounts-sync.spec.js
⚠️  Please do not merge yet until this feature is available in the platform ⚠️ 
Closes #374
=> feat(sync-actions/product-discounts): add validFrom and validUntil

packages/sync-actions/src/customer-group.js, packages/sync-actions/test/customer-group-sync.spec.js
Adds custom fields to customer groups. This PR adds it the same way we added it for cart discounts and discount codes etc. It also contains the same restructuring of the specs.
=> feat(sync-actions): add custom fields to customer groups

packages/sync-actions/src/tax-categories-actions.js, packages/sync-actions/src/tax-categories.js, packages/sync-actions/test/tax-categories-sync.spec.js
add sync actions for tax categories
This PR adds the sync actions for the tax categories.
=> feat(sync-actions): add sync actions for tax categories

packages/sync-actions/src/product-actions.js, packages/sync-actions/src/utils/extract-matching-pairs.js, packages/sync-actions/test/utils/extract-matching-pairs.spec.js
Extracting this utility out of [`product-actions`](https://github.com/commercetools/nodejs/blob/master/packages/sync-actions/src/product-actions.js#L157-L172)
This is needed as well for attributes and enums on the [product-types-actions](https://github.com/commercetools/nodejs/blob/aa-add-product-types-sync-actions/packages/sync-actions/src/product-types-actions.js#L53-L58).
Import on the product-actions will follow.
=> feat(sync-actions): add `extract-matching-pairs`

packages/csv-parser-discount-code/package.json, packages/csv-parser-discount-code/src/index.js, packages/csv-parser-discount-code/src/main.js, packages/csv-parser-discount-code/test/main.spec.js
Support parsing of (discount-code)[https://dev.commercetools.com/http-api-projects-discountCodes.html#discountcode] groups in CSV for importing
Also contains minor refactorings to make code more readable, removes the redundant `index.js` file, and removes `lodash` dependency (Minor step in "delodashing" this repo 😃)
resolves #431
=> 431 code groups csv parser

docs/cli/product-exporter.md, docs/sdk/Middlewares.md, docs/sdk/api/README.md, docs/sdk/api/sdkMiddlewareAuth.md, packages/sdk-middleware-auth/src/existing-token.js, packages/sdk-middleware-auth/src/index.js, packages/sdk-middleware-auth/test/existing-token.spec.js, types/sdk.js
Add middleware for directly attaching token to  request headers
Related to #446 this package adds the middleware to attach an already known access token to the request header
It will be nice to get input on a few things before this gets merged:
- The object properties used are `token`, `tokenType` and `force`. Does this method make sense? Are `force` and `tokenType` necessary? should they be renamed to `accessToken`, `access_token`, `accessTokenType`, `access_token_type`, etc?
- Also, I implemented it such that it simply passes the request and response to the next middleware if there is no token passed in? I think this makes sense in certain situations such as modules that can be built to use this middleware, or an authentication flow if there is no access token. Does this make sense? …
=>  feat(auth-middleware): add middleware for existing token

packages/sync-actions/src/zones-actions.js, packages/sync-actions/test/zones.spec.js
This PR fixes some issues that appear during the UX/UAT that were indeed related to the sync-actions of zones.
I've added some code comment to explaining the use cases. Hope that makes sense 👍 
Basically there were some cases that the sync-actions were not handling correctly guiding us to some UI errors (API errors) in the MC FE.
Working example. Let's say I have this object:
`locations: [{country: 'Spain'} ,{country: 'Germany'}]`
And my new object is:
`locations: [{country: 'Germany'}]`
The sync actions builded were:
```js
[
{action: "removeLocation", location: {country: "Spain"}},
{action: "addLocation", location: {country: "Germany"}},
{action: "removeLocation", location: {country: "Germany"}}
] 
```
That set of actions leads us to an API error …
=> fix(zones-locations): fix zone locations updates

docs/sdk/api/sdkMiddlewareHttp.md, packages/sdk-middleware-http/src/http.js, types/sdk.js
When working with HTTP Cookies, the SDK HTTP middleware should be able to be configured to set the `credentials` mode (https://github.com/github/fetch#sending-cookies).
Adds a new option `credentialsMode` to the `createHttpMiddleware`.
NOTE: I wasn't able to properly write a test for this, it's kind of tricky to reach into the internals of `fetch`.
=> feat(sdk-middleware-http): allow to pass credentials mode to fetch object

packages/sync-actions/src/tax-categories-actions.js, packages/sync-actions/test/tax-categories-sync.spec.js
**Summary**
This PR fixes an issue when doing multiple complex actions with tax categories rates.
I've added some test for this use case. Hope that makes sense 👍
**Description**
We were not taking into account if we were updating the correct rate in the `replaceTaxRate`, specially when we delete and update rates. I guess is because how the diff is returned.
NOTE--> I've already slap Dani for this 😝💪
```js
// before
rates: [{ id: 1, name: 'A' }, { id: 2, name: 'B' }]
// now
rates: [{ id: 2, name: 'C' }]
// Expected behaviour
actions: [{
{
action: 'replaceTaxRate',
taxRate: { id: 2, name: 'C' },
taxRateId: 2,
},
{ action: 'removeTaxRate', taxRateId: 1 }, // removed first tax rate
}]
// Observed behaviour
actions: [{
{
action: 'replaceTaxRate',
taxRate: { …
```
=> fix(tax-categories-actions): Fix issue when doing multiple complex actions on rates

packages/sdk-middleware-http/src/http.js, packages/sdk-middleware-http/test/http.spec.js
When API returns an error respons, e.g. 404 not found, we leak authorization token in error object. I will create another ticket for an eventual change to `maskSensitiveHeaderData` so it defaults to `true`
- Tests
resolves #518
=> fix(HTTP): Make error maskSensitiveHeaderData

packages/csv-parser-state/src/main.js, yarn.lock
For compatibility reasons PR replaces async/await with promises. This also removes the need to have the babel runtime dependency in production
=> refactor(state-parser): replace async/await with promises

packages/sdk-middleware-http/src/http.js, packages/sdk-middleware-http/test/http.spec.js
Follow up PR to #524 as we found that both `authorization` and `Authorization` is used in the headers so we need to mask both. Also refactored to use `maskAuthData` function for all errors.
=> fix(HTTP): mask both 'Auth' and 'auth' data in all errors

docs/cli/csv-parser-orders.md, integration-tests/cli/__snapshots__/csv-parser-orders.it.js.snap, packages/csv-parser-orders/src/cli.js, packages/csv-parser-orders/src/constants.js
PR enables encoding option (default is `utf8`).
Client was reporting a bug where they could not update orders with CSV's that used `hex` encoding instead of default `utf8`. PR will enable them to use this. 
resolves #532
=> feat(order-update): Implement encoding flag for CSV

docs/sdk/api/apiRequestBuilder.md
Fixed typo in API Request Builder doc
There is a typo in the API Request Builder doc. It has `url` in the request object and that fails. Correct key is `uri`.
=> Fixed typo in API Request Builder doc

.babelrc
Update .babelrc settings for production and cli environment
resolves #561
=> chore(babel): compile production and cli to node 6 instead of 4

packages/product-json-to-csv/src/writer.js, packages/product-json-to-csv/test/__snapshots__/writer.spec.js.snap, packages/product-json-to-csv/test/helpers/csvFileWithDelimiter.csv, packages/product-json-to-csv/test/helpers/csvFileWithHeaders.csv, packages/product-json-to-csv/test/helpers/productType1Sample.csv, packages/product-json-to-csv/test/helpers/productType2Sample.csv, packages/product-json-to-csv/test/writer.spec.js
PR sets quotes option when using [json2csv](https://www.npmjs.com/package/json2csv) package to default (")
We had problems were a client was using commas(,) in their description of the products. Without encapsulating the cell values in quotes the CSV parser would push data to the next cell. This also happened when client chose to use pipes(|) as their delimiter since images return both the file path as well as pixel dimensions within pipes. Such as `<file/Path.jpg>|120|120|`
PR also refactors tests to use snapshots which, also, includes the new quotes.
* Tests
resolves #557
=> fix(product-json-to-csv): use default quotes value(")

packages/product-json-to-csv/src/map-product-data.js, packages/product-json-to-csv/test/__snapshots__/map-product-data.spec.js.snap, packages/product-json-to-csv/test/map-product-data.spec.js
affects: @commercetools/product-json-to-csv
Fixes a bug where `multiValueDelimiter` was not used in images. Also removes `dimensions` attributes as they are not needed.
* Tests
closes #565
closes #566
=> fix(product-json-to-csv): use multivaluedelimiter and remove dimensions

integration-tests/cli/product-export.it.js, packages/product-exporter/src/main.js
PR makes product-export throw error `No products found` when predicate is too strict or there simply isn't any products.
We used to export empty JSON files which 
a) Doesn't make sense to clients as they would prefer to get an error instead of downloading an empty file.
b) Caused `json-to-csv` parser package to break since it is not built to handle empty JSON files.
Note that this is a breaking change so we need to make sure everyone is aware of the new behaviour.
resolves #553
=> fix(product-export): throw error when no products are found

packages/sync-actions/src/products.js, packages/sync-actions/test/product-sync-variants.spec.js, yarn.lock
move attribute actions above variant actions
resolves #589 
See #589 for more context on this issue
=> fix(sync-actions): re-order product update actions build sequence

packages/sync-actions/src/product-types-actions.js, packages/sync-actions/test/product-types-sync-enums.spec.js
- generates update-actions for changes in enum
- removes `get*` and use simpler assignment
for the moment, the `sync-actions/products` assumes the following shape of the attribute when the type is enum;
```
{
type: {
name: 'enum'
}
values: []
}
```
which results `sync-actions` not generating appropriate update actions when there is a change in `values` of enums.
```js
{
type: {
name: 'enum'
values: []
}
}
```
* Tests
=> fix(sync-actions/product-types): product types doesn't generate update actions for enum changes

docs/sdk/api/syncActions.md, packages/sync-actions/src/product-types-actions.js, packages/sync-actions/src/product-types.js, packages/sync-actions/src/utils/common-actions.js, packages/sync-actions/test/product-types-sync-base.spec.js, types/sdk.js
- add configuration to `createSyncProductTypes` to treat empty string as not a value
- follow up to https://github.com/commercetools/nodejs/pull/541
So at the project I work on, we still use work-arounds to treat empty string, `undefined` and `null` as not a value in our forms. This is something that we wish is already supported on the `nodejs/sync-actions`.
Unfortunately, on #541 we learned that the changes in that PR is a breaking change across all sync-action types and can potentially break clients using the `nodejs/sync-actions` and still has the use case of __empty string being a value__
This time I suggest it to be an __opt-in__
For now, I added support only on product-types. We can add support to other types as a separate step essentially when it is needed. There won't be much …
=> feat(sync-actions): configure empty string as not-a-value

docs/sdk/api/README.md, docs/sdk/api/sdkMiddlewareAuth.md, docs/sdk/api/sdkMiddlewareHttp.md, docs/sdk/api/sdkMiddlewareLogger.md, docs/sdk/api/sdkMiddlewareQueue.md, docs/sdk/api/sdkMiddlewareUserAgent.md
Summary
Fix typo's in docs
Description
Small typos in docs where Middleware is misspelled as Middelware.
closes #616
=> docs(docs): fix typo's in docs

packages/csv-parser-discount-code/package.json, packages/csv-parser-orders/package.json, packages/csv-parser-price/package.json, packages/csv-parser-state/package.json, packages/custom-objects-exporter/package.json, packages/discount-code-exporter/package.json, packages/inventories-exporter/package.json, packages/price-exporter/package.json, packages/product-exporter/package.json, packages/product-json-to-csv/package.json, yarn.lock
affects: @commercetools/csv-parser-discount-code, @commercetools/csv-parser-orders,
@commercetools/csv-parser-price, @commercetools/csv-parser-state,
@commercetools/custom-objects-exporter, @commercetools/discount-code-exporter,
@commercetools/inventories-exporter, @commercetools/price-exporter, @commercetools/product-exporter,
@commercetools/product-json-to-csv
PR sets exact version of JSONStream as recent patch introduced memory leakage. More info in [issue](https://github.com/commercetools/nodejs/issues/624)
resolves #624
=> fix(deps): set exact version of JSONStream dep

packages/product-json-to-csv/readme.md
Wrong link in product-json-to-csv package readme
We have a wrong link to a documentation in README.md file in product-json-to-csv package:
https://commercetools.github.io/nodejs/cli/json-parser-products.html
Correct link is:
https://commercetools.github.io/nodejs/cli/product-json-to-csv.html
Closes #623
=> docs(product-json-to-csv): Set correct link in readme

packages/sync-actions/src/product-actions.js, packages/sync-actions/test/product-sync-images.spec.js
Fixes spelling error for `moveImageToPosition` action.
Correct spelling is [here](https://docs.commercetools.com/http-api-projects-products#move-image-to-position) in the docs.
resolves #638
=> fix(sync-actions): fix misspelled moveImageToPosition action

.renovaterc.json
Since we use semver ranges instead of pinning the dependencies our [readme](https://github.com/commercetools/nodejs/blob/master/README.md) hurts people's eyes by saying our packages are **insecure** or **out of date**.
PR proposes to pin all dependencies and not only the `dev dependencies`
=> chore(renovate): pin all dependencies

packages/sync-actions/src/cart-discounts.js, packages/sync-actions/src/discount-codes.js, packages/sync-actions/src/product-discounts.js, packages/sync-actions/src/utils/combine-validity-actions.js, packages/sync-actions/test/cart-discounts-sync.spec.js, packages/sync-actions/test/discount-codes-sync.spec.js, packages/sync-actions/test/product-discounts-sync.spec.js, packages/sync-actions/test/utils/combine-validity-actions.spec.js
In this PR we add support we combine both  `setValidFrom` and `setValidUntil` to `setValidFromAndUntil` when appropriate 
- Add utility function that combines `validFromAction` and `validUntilAction` if both exist
- Apply `combineValidityActions` to discounts
When we apply list of actions, and one of them fails, all fail, which is great.
But in some situation like the following example
**Draft**
```js
{
validFrom: '01.01.2019',
validUntil: '10.01.2019'
}
```
**Updated values**
```js
{
validFrom: '15.01.2019',
validUntil: '20.01.2019'
}
```
this will generate two update actions
```
[
{setValidFrom: '15.01.2019'},
{setValidUntil: '20.01.2019'}
]
```
And when applying the first action _setValidFrom_ we'll have this middle state 
```js
{
validFrom: '15.01.2019',
validUntil: '10.01.2019'
}
``` …
=> Add set valid from and until action for discounts

.renovaterc.json
Using [:pinVersions preset](https://renovatebot.com/docs/presets-default/#pinversions) makes renovate bot pin the node engine, like seen in this PR #674
This PR changes the config to pin everything except engines. Verified working in this PR in forked repo.
https://github.com/daern91/nodejs/pull/4/files
This also removes `group:monorepos` as it is already included in `config:base
`, [more info here](https://renovatebot.com/docs/presets-config/#configbase).
closes #674
=> fix(renovate): disable auto update of node engines

lerna.json
PR makes sure we pin all dependencies upon publish.
After recent changes to pin all dependencies instead of using ranges, we found that lerna publishes with added carets to the package.json. This makes renovate directly respond with a new PR that pins the dependencies again. Which in-turn makes lerna think the packages have changes and are ready to be published again. This could keep going forever...
PR adds `"exact": true` to `lerna.json` to fix this. This functionality was added to lerna [in this commit](https://github.com/lerna/lerna/pull/661/files#diff-7f56aae935ac7120955d2dc2fbf62eb8).
For more reading, please see lerna docs [here](https://github.com/lerna/lerna/tree/master/commands/version#--exact).
resolves #722
=> chore(tooling): pin deps when publishing instead of using ranges

.renovaterc.json
We are currently extending Renovate's [base config](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-config/package.json#L16-L34) which sets the concurrent PR limit to 20. This causes some trouble right now as we have more updates that needs to get done throughout all the packages and should not wait until next week to have them done.
So, this PR removes the limitation through adding the `prConcurrentLimitNone` option that got introduced in this PR: https://github.com/renovatebot/presets/pull/77
=> chore(renovate): remove limitation of concurrent pull requests

packages/sync-actions/src/orders.js, packages/sync-actions/test/order-sync.spec.js
Adds support for order custom fields.
We are improving how we handle custom fields in the MC and when developing this for orders, I've realized that we didn't add the support for the `custom` attribute in orders 👍 
I've based the solution on what we have in `channels` and `customers` since is working like a charm there 😋 . Hope it make sense!
- Tests
=> (sync-actions): support custom fields updates in orders

lerna.json
We had forgot to update the config to use latest version...
https://github.com/commercetools/nodejs/blob/0e6a4574fe4e2f6741bdd22df783134bcdaeb57c/package.json#L90
=> chore: update lerna config

packages/sdk-auth/src/auth.js, packages/sdk-auth/test/password-flow.spec.js, packages/sdk-auth/test/refresh-token-flow.spec.js, packages/sdk-auth/test/token-introspection.spec.js
Refactor for easier use with `.cjs`
- Tests
=> refactor(sdk-auth): use promises instead of async-await

docs/sdk/api/apiRequestBuilder.md, packages/api-request-builder/src/build-query-string.js, packages/api-request-builder/src/default-params.js, packages/api-request-builder/src/query-page.js, packages/api-request-builder/test/build-query-string.spec.js, packages/api-request-builder/test/default-params.spec.js, packages/api-request-builder/test/query-page.spec.js, types/sdk.js
The api request builder should support withTotal of the API. This is needed for performance improvements within the MC.
Reference: https://docs.commercetools.com/http-api#pagedqueryresult
=> Add support of withTotal to api-request-builder

docs/sdk/api/sdkAuth.md, package.json, packages/sdk-auth/src/auth.js, packages/sdk-auth/test/custom-flow.spec.js, types/sdk.js
This PR adds a possibility to specify custom headers when doing a customFlow auth request.
- Tests
=> feat(sdk-auth): add a possibility to specify custom headers

packages/product-json-to-csv/src/map-product-data.js, packages/product-json-to-csv/test/__snapshots__/map-product-data.spec.js.snap, packages/product-json-to-csv/test/map-product-data.spec.js, yarn.lock
Fixes #970 
When exporting a product with no product description field but an attribute named as description, we save incorrectly the attribute to `description` column instead of prefixing it with an `attribute.` string.
This PR adds a list of conflicting names which should be prefixed.
- Tests
=> fix(product-json-to-csv): fix prefixing of conflicting attribute names

.circleci/config.yml, package.json, packages/category-exporter/package.json, packages/csv-parser-state/package.json, packages/custom-objects-exporter/package.json, packages/customer-groups-exporter/package.json, packages/personal-data-erasure/package.json, packages/product-exporter/package.json, packages/product-json-to-csv/package.json, packages/product-json-to-xlsx/package.json, packages/sdk-auth/package.json, packages/sdk-middleware-auth/package.json, packages/sdk-middleware-http/package.json, yarn.lock
Dependencies update 
Dependencies update of the following:-
- circleci/node:6 docker digest to 4dc9e63
- circleci/node:8 docker digest to 2ccff04
- babel monorepo from v7.2.0 to v7.2.3
- debug from v4.1.0 to v4.1.1
- eslint from v5.10.0 to v5.11.1
- nock from v10.0.4 to v10.0.5
- resolve from v1.8.1 to v1.9.0
- rollup from v0.68.0 to v0.68.2
- pino from v5.10.1 to v5.10.5
resolves #1035
resolves #1036
resolves #1037
resolves #1039
resolves #1040
resolves #1041
resolves #1042
resolves #1043
resolves #1044
=> chore(deps): update deps

.circleci/config.yml, .flowconfig, package.json, packages/category-exporter/package.json, packages/csv-parser-orders/package.json, packages/csv-parser-price/package.json, packages/csv-parser-state/package.json, packages/custom-objects-exporter/package.json, packages/customer-groups-exporter/package.json, packages/get-credentials/package.json, packages/personal-data-erasure/package.json, packages/product-exporter/package.json, packages/product-json-to-csv/package.json, packages/product-json-to-xlsx/package.json, yarn.lock
Update deps
Dependencies update of the following:-
- circleci/node:8 docker digest to b0b6b8d
- @commitlint/cli from v7.3.1 to v7.3.2
- eslint from v5.12.0 to v5.12.1
- eslint-config-prettier from v3.4.0 to v3.6.0
- eslint-formatter-pretty from v2.0.0 to v2.1.1
- eslint-plugin-react from v7.12.3 to v7.12.4
- flow-bin from v0.90 to v0.91.0
- leasot from v7.0.0 to v7.1.0
- prettier from v1.15.3 to v1.16.0
- rollup from v1.1.0 to v1.1.2
- rollup-plugin-babel from v4.3.0 to v4.3.2
- sinon from 7.2.2 to v7.2.3
- stream-to-string from v1.1.0 to v1.2.0
- pino from v5.10.6 to v5.10.8
resolves #1086
resolves #1087
resolves #1088
resolves #1089
resolves #1090
resolves #1091
resolves #1092
resolves #1093
resolves #1094
resolves #1095
resolves #1096
resolves #1097
resolves #1098
resolves #1099
=> chore(deps): deps update

docs/cli/category-exporter.md, docs/cli/custom-objects-exporter.md, docs/cli/customer-groups-exporter.md, docs/cli/discount-code-exporter.md, docs/cli/price-exporter.md, docs/cli/product-exporter.md
Fix broken Link to query predicate docs.
The query predicate documentation link in README files of CLIs is not valid anymore.
It is changed from https://docs.commercetools.com/http-api.html#predicates to https://docs.commercetools.com/http-api-query-predicates
Closes #1131
=> docs(): fix broken query predicate docs link

TODOS.md, integration-tests/cli/helpers/product-json2csv.data.js, integration-tests/cli/product-json-to-csv.it.js, packages/product-json-to-csv/src/main.js, packages/product-json-to-csv/src/map-product-data.js, packages/product-json-to-csv/test/main.spec.js, types/product.js
PR adds missing functionality to include the customerGroup when exporting product prices
For some reason, this was never implemented. PR should be straight-forward as it's only extending parts of the current code.
- Tests
closes #1166
=> feat(product-json-to-csv): add customerGroup to product prices

integration-tests/sdk/auth.it.js
Fix failing auth integration tests
This PR fix the failing integration tests ([details](https://circleci.com/gh/commercetools/nodejs/10624)).
The `anonymous_id` and `customer_id` are needed in order to generate a `refresh token` which is a mandatory requirement to obtain an `access token`.
This is as a result of the newly added feature to the SDKs for external OAuth. For more details, see [here](https://github.com/commercetools/docs.commercetools.com/pull/1255).
- Tests
Closes #1203
=> test(auth.it.js): Fix failing auth integration test

packages/sync-actions/src/customer-actions.js, packages/sync-actions/test/customer-sync.spec.js
ISSUES CLOSED: 1240
This PR adds locale for the sync-actions for customers.
- Tests
Closes #1240
=> fix: add locale action in customer sync actions

packages/sync-actions/src/utils/common-actions.js, packages/sync-actions/test/customer-sync.spec.js
This PR fixes the `sync-actions` for customer resource `id` undefined error and allows the customerGroup property of a customer to be set using `key` as a reference.
- Tests
Closes #1229
=> fix(sync-actions): customer resourceId undefined error

docs/cli/inventories-exporter.md, integration-tests/cli/__snapshots__/inventories-exporter.it.js.snap, packages/inventories-exporter/src/cli.js, packages/inventories-exporter/src/main.js, packages/inventories-exporter/test/main.spec.js, types/inventory.js
This PR adds a possibility to provide a template with fields which should be exported when mapping inventory entries to CSV.
Resolves #1268
- Tests
=> feat(inventories-exporter): add a possibility to export predefined fields

packages/category-exporter/src/main.js, packages/custom-objects-exporter/src/main.js, packages/customer-groups-exporter/src/main.js, packages/discount-code-exporter/src/main.js, packages/inventories-exporter/src/main.js, packages/price-exporter/src/main.js, packages/product-exporter/src/main.js
PR enables retries for all exporter packages as users had problems on larger exports where some requests would timeout. That would then abort the whole export.
resolves #1293
=> fix(exporters): enable request retries

CHANGELOG.md, packages/sdk-auth/src/auth.js, packages/sdk-middleware-auth/src/build-requests.js, packages/sdk-middleware-auth/test/refresh-token-flow.spec.js
PR fixes problem where tokens would not be encoded and, thus, fail whenever they contained a non-ascii character as the query string would be wrong.
- Tests
resolves #1333
=> fix(auth): correctly encode token

packages/api-request-builder/src/default-services.js, packages/api-request-builder/test/create-request-builder.spec.js
The API design is a bit strange in this case as the `active cart` lies under its own endpoint as `/me/active-cart` and does not follow the design of the others like `/me/carts/whatever` ([doc ref](https://docs.commercetools.com/http-api-projects-me-carts#get-active-cart)). 
Therefore, we opted to put it as a service and be built as `requestBuilder.myActiveCart.build()`
resolves #1338
=> feat(api-req-builder): add myActiveCart as a service

packages/sync-actions/src/assets-actions.js, packages/sync-actions/src/categories.js, packages/sync-actions/test/category-sync.spec.js
This PR adds support for synching category assets to our `synch-actions` module.
This implementation is the simplest solution for synching category assets and follows the approach we use for product variants:
- we only use `addAsset` and `removeAsset` update action instead of using the more fine grained asset update actions (e.g. `changeAssetName`)
- Tests
=> feat(sync-actions): add sync actions for category assets

CHANGELOG.md
Manually adds missing breaking changes to the changelog. We should also look into why lerna/commitizen is not updating this correctly.
references #1332
=> chore: add missing breaking changes to changelog

packages/sync-actions/src/utils/action-map-custom.js, packages/sync-actions/test/utils/action-map-custom.spec.js
This PR fixes sync-actions for using key as a resource identifier in setting custom fields/types.
- Tests
=> fix(sync-actions): add key in setting custom types 

TODOS.md, packages/api-request-builder/src/query-search.js, packages/api-request-builder/test/query-search.spec.js
PR enables setting `fuzzyLevel` to 0.
We were checking for falsey values in the conditional. And since `0` evaluates to falsey it was not possible to use it. More info in the referenced issue below.
- Tests
resolves #1348
=> fix(req-builder): enable setting fuzzyLevel to 0

packages/product-json-to-csv/src/main.js, yarn.lock
PR adds batching to `get requests` with `channel` and `custumerGroup` predicates.
Previously, we were just stacking them all up which could lead to requests with hundreds of IDs. These requests would then be denied by our platform load balancer which is not configurable. 
resolves #1377
=> fix(product-json-to-csv): split requests with too large predicate

packages/sdk-middleware-auth/src/build-requests.js, packages/sdk-middleware-auth/test/base-auth-flow.spec.js
This PR removes authScopes.MANAGE_PROJECT as aoujth2 default scope.
Instead of sending a default scope we now don't send any scope. The resulting scope thus will be the scope of the given api client.
Closes #1382 
- Tests
=> fix(sdk-middleware-auth): remove authScopes.MANAGE_PROJECT as default scope

packages/sync-actions/src/customer-actions.js, packages/sync-actions/test/customer-sync.spec.js
This pull request adds the ability to sync customer salutations to sync actions.
This feature has been demanded for the MC.
[API Reference](https://docs.commercetools.com/http-api-projects-customers#set-salutation).
Rough look
=> feat(sync-actions): add setSalutation to customer sync

packages/api-request-builder/src/create-service.js, packages/api-request-builder/src/default-params.js, packages/api-request-builder/src/query-id.js, packages/api-request-builder/test/create-service.spec.js, types/sdk.js
PR adds functionality to get custom objects by [container and ID](https://docs.commercetools.com/http-api-projects-custom-objects#get-customobject-by-container-and-key).
- Tests
resolves #1358
=> feat: querying custom objects by container and key

TODOS.md, babel.config.js, docs/sdk/api/sdkMiddlewareHttp.md, packages/sdk-middleware-http/package.json, packages/sdk-middleware-http/src/http.js, packages/sdk-middleware-http/test/http.spec.js, types/sdk.js, yarn.lock
PR adds `timeout` and `AbortController` options to the http middleware. When using the timeout option, we opted for using the controller over the `timeout` option which is available on some fetch implementations. This decision was based on the fact that `timeout` is getting deprecated in most common fetchers, including [node-fetch](https://www.npmjs.com/package/node-fetch#options). Instead, they are following the guidelines from the [Fetch Standard](https://fetch.spec.whatwg.org/) where `timeout` does not exist.
More reading and info here https://github.com/bitinn/node-fetch/issues/523
In addition, this allows users to implement their own abort mechanisms by simply passing in the controller without using the timeout.
- Tests
resolves #190
=> feat(http-middleware): custom timeout and abortcontroller options

.renovaterc.json
This aligns the renovate config with what we use in other repos. Basically we get every Monday up  to 3 PRs:
- lockfile maintenance
- all deps (non major)
- all deps (major)
Example from appkit:
=> chore: align renovate config with other repos

packages/api-request-builder/src/default-params.js, packages/api-request-builder/test/create-request-builder.spec.js, packages/api-request-builder/test/default-params.spec.js
Closes #1446
The key param is not a query parameter and it thus wasn't properly handled. I added reseting of the key param to our `setDefaultParams` function and added a test to make sure that it works.
- Tests
=> fix(api-request-builder): reset key

.flowconfig, packages/product-json-to-csv/src/map-product-data.js, packages/product-json-to-csv/test/__snapshots__/map-product-data.spec.js.snap
Add support for Dimensions in image url when export the products
below is example
https://jeanscentre-static.joggroup.net/sys-master/images/ha9/hf0/9027232661534/871821258791|ProductImage|100x100
closes #1460
=> feat(product): add support for dimensions in image url

packages/typescript-sdk/src/generated/base/requests-utils.ts, packages/typescript-sdk/test/generated/base/request-utils.spec.ts
This PR fixes the serialization of Array query parameters and simplifies it by using the build in `querystring.stringify` function.
Fixes #1462 
I tried to find a place where tests for this is written, but couldn't find any. Do you have a plan for unit testing the typescript-sdk? It would be helpful to prevent these sort of bugs. I know this bit is generated, but that doesn't mean it cannot contain bugs.
- Tests
=> fix(ts-sdk): serialization of array query parameters

packages/sync-actions/src/customer-actions.js, packages/sync-actions/test/customer-sync.spec.js
- adds `setStores`. ref https://docs.commercetools.com/http-api-projects-customers#set-stores-beta
This is to prepare for a feature in the MC
=> feat(sync/customers): add `setStores`

integration-tests/cli/csv-parser-price.it.js, packages/csv-parser-price/src/cli.js, packages/csv-parser-price/src/main.js, packages/csv-parser-price/test/helpers/invalid-sku-sample.csv, packages/csv-parser-price/test/main.spec.js
=> fix(csv-parser-price): handle error when variant-sku key is missing/mis-spelled

package.json, packages/sdk-types/package.json, packages/sdk-types/tsconfig.json, packages/typescript-sdk/package.json
Lerna provide a way to call script from root project.
```
lerna run some-command
```
Lerna will look for  some-command inside all the package and if found will run.
=> chore(typescript): move typescript check at package level from root

packages/sync-actions/src/shipping-methods-actions.js, packages/sync-actions/test/shipping-methods.spec.js
Shipping methods now support a localized description. This decription is planned to eventually replace the non-localized description. As we intend to add this as a field to the MC we also need it in the sync-actions.
API Documentation: https://docs.commercetools.com/http-api-projects-shippingMethods#set-localized-description
The PR is fairly self explanatory I think. I just followed what's there and added a field.
=> feat(sync-actions): add localized description for shipping methods

.flowconfig, packages/sync-actions/src/categories.js, packages/sync-actions/src/utils/copy-empty-array-props.js, packages/sync-actions/test/category-sync.spec.js
Fix and Test sync-action 
Fixing issue which happen with the below code
`
const before = {
assets: [],
}
const now = {
}
const actual = categorySync.buildActions(now, before)
`
the following error is thrown:
`
Cannot read property '0' of undefined
`
- Tests
- [ x] Unit
- [ x] Documentation
=> fix(sync-actions): bug where we throw on empty assets in categories

packages/sync-actions/src/cart-discounts-actions.js, packages/sync-actions/test/cart-discounts-sync.spec.js
Add `setKey` to CartDiscounts list of actions
Adding coverage to the cart discounts sync actions by detecting the `setKey` update action.
=> feat(sync-actions): adding set key action for cart-discounts

packages/sync-actions/src/customer-actions.js, packages/sync-actions/src/product-discounts-actions.js, packages/sync-actions/src/zones-actions.js, packages/sync-actions/test/cart-discounts-sync.spec.js, packages/sync-actions/test/customer-sync.spec.js, packages/sync-actions/test/product-discounts-sync.spec.js, packages/sync-actions/test/zones.spec.js
Adding `setkey` to `Product Discount`, `Customer` and `Zone`
Adding the detection of the `setKey` action for the following resources:
- `Product Discount`
- `Customer` 
- `Zone`
Adding the corresponding tests for each resource type.
=> feat(sync-actions): add set key actions

packages/api-request-builder/src/create-service.js, packages/api-request-builder/src/default-params.js, packages/api-request-builder/src/query-id.js, packages/api-request-builder/test/create-service.spec.js, packages/api-request-builder/test/query-id.spec.js, types/sdk.js
Add order number support on order service
- added function `byOrderNumber` 
- added orderNumber key to uri
=> feat(request-builder): add orderNumber support on order service

packages/api-request-builder/src/default-services.js
Update wrong endpoints
Changed the endpoint for both 'customersEmailVerificationToken' and 'customersEmailVerification'.
affects: @commercetools/api-request-builder
=> fix(default-services): change wrong endpoints

packages/api-request-builder/src/default-services.js, packages/api-request-builder/test/create-request-builder.spec.js
Adding `stores` to `api-request-builder` package
Currently the package does not support  `stores`  endpoint, this PR intends to add that coverage.
=> feat(api-request-builder): adding stores to the package

packages/sync-actions/src/utils/copy-empty-array-props.js
I saw that the tests failed since node 10 didn't support `fromEntries`. PR stops relying on this function and instead builds the object with help of reduce.
=> fix: use reduce instead of fromPairs

packages/sync-actions/src/utils/copy-empty-array-props.js, packages/sync-actions/test/utils/copy-empty-array-props.spec.js
This PR removes the side effect from our `copyEmptyArrayProps` function.
=> fix(sync-actions): remove side effect from copyEmptyArrayProps function

packages/sync-actions/src/stores-actions.js, packages/sync-actions/test/stores-sync.spec.js
- adds support `setDistributionChannels` 
Context added this update-action recently to the Stores API.
It may look like it is not documented. It is documented, however we are waiting for the MC feature to be released before we release the documentation.
please view.
=> feat(sync-actions/stores): add `setDistributionChannels`

packages/csv-parser-price/package.json, packages/csv-parser-price/src/main.js, packages/csv-parser-price/test/helpers/utf-bom.csv, packages/csv-parser-price/test/main.spec.js
=> fix(csv-parser-price): handle UTF-8 with BOM encoding while price import

packages/sync-actions/src/customers.js, packages/sync-actions/src/inventories.js, packages/sync-actions/test/inventory-sync.spec.js
Currently changes over `CustomType` and `CustomField` are not being detected by the sync actions
Adding the group of custom actions and the corresponding tests
=> feat(SyncActions): Add CustomType actions in inventory entries

packages/sync-actions/src/products.js, packages/sync-actions/test/product-sync-prices.spec.js
Fix for issue [1561](https://github.com/commercetools/nodejs/issues/1561)
Generating `PriceCustom` actions before `changePrice` to fix actions overloading each other.
The ordering of the actions tested via Impex
=> fix(sync-actions): generate PriceCustom actions before changePrice

packages/sync-actions/src/stores-actions.js, packages/sync-actions/test/stores-sync.spec.js
- adds `setSupplyChannels` for stores
- same deal as https://github.com/commercetools/nodejs/pull/1530#issue-407171862. It may look like it is missing documentation, but Context team will wait until the MC feature is released before we release the doc update.
=> feat(sync-actions/stores): add set supply channels

packages/category-exporter/package.json, packages/csv-parser-state/package.json, packages/custom-objects-exporter/package.json, packages/custom-objects-importer/package.json, packages/customer-groups-exporter/package.json, packages/inventories-exporter/package.json, packages/personal-data-erasure/package.json, packages/price-exporter/package.json, packages/product-exporter/package.json, packages/product-json-to-csv/package.json, packages/product-json-to-xlsx/package.json, packages/resource-deleter/package.json, packages/state-importer/package.json
- update emails from `*.de -> *.com`
I saw some older emails of people who no longer are in the company. if you want ownership to change, leave a **suggestion** that can be commited on the PR.
=> chore: update emails commercetools.de -> commercetools.com

packages/sdk-auth/package.json, packages/sdk-auth/src/auth.js, packages/sdk-auth/test/client-password-flow.spec.js, packages/sdk-auth/test/common.spec.js, packages/sdk-auth/test/customer-password-flow.spec.js, packages/sdk-auth/test/token-introspection.spec.js, yarn.lock
This pull request fixes the `sdk-auth` package to encode the request's body at all times.
The `sdk-auth` is used to perform request authorization in our Node.js SDK. For that it often uses parameters such as `scope`, `refresh_token` or `grant_type` among others.
The parameters mentioned above can often contain strings which need encoding. This holds true for e.g. the `<scope>:<projectKey>` or also the `token` itself.
So far the `sdk-auth` just concatinated strings to build up the request. For example as `body += `&scope=${scope}`. Then sometimes it encodes a parameter as `request.body += `&refresh_token=${encodeURIComponent(token)}`. Our APIs can deal with this inconsistency but it can also cause problems when a string is not rightfully detected as not encoded. This is what I think …
=> fix(sdk-auth): to encode request body

packages/sync-actions/src/products.js, packages/sync-actions/test/product-sync-base.spec.js
Give the ability to publish product actions directly by simply mark `staged` flag to false.
One use case for this, it would make it easy for package user to just publish the updates instead of sending update actions then send another action to publish product updates plus this feature would shorten the platform calls
=> feat(sync-actions): publish product actions

packages/api-request-builder/src/default-services.js
=> fix(api-request-builder): Add expand for custom object API

packages/sdk-middleware-http/src/http.js, packages/sdk-middleware-http/test/http.spec.js
When returning empty 200,202,204 etc from external api the sdk throws. This change catches the exception from res.json() and continues with a default empty object in case the parsing fails, as long as the response status is ok. 
It's not uncommon to use 'return Accepted()` or return `Ok()` in asp core and even though specifying the content type as json the return will be empty making json() throw. The content length header seems to be stripped in the proxy so the simplest solution for handling a common server solution for empty 202, 204, and 200 seems to be to catch the exception and continue with an empty body.
- Make a post to an external api from a custom application. 
- Have the server respond with an empty 202. (i.e asp core `return Accepted()` or `return Ok()`)
- Tests
=> Remove dependence on content in ok result when executeFetch

packages/sync-actions/src/stores.js, packages/sync-actions/test/stores-sync.spec.js
- `sync-actions/stores` => The CTP GraphQL API supports custom fields on Store type. Therefore, this PR enables the `nodejs` sdk users to update/add custom fields to Store.
- CTP GraphQL has added custom field support on Store type.
_Creating store graphql input draft_
_Updating store graphql input draft_
This PR updates the nodejs sdk to support these actions.
=> feat(sync-actions/stores): add support custom fields actions on store level

packages/resource-deleter/src/main.js
The queue middleware was not working in the resource deleter
- Tests
=> Queue middleware misplaced in resource deleter

packages/sync-actions/src/customer-actions.js, packages/sync-actions/src/customers.js, packages/sync-actions/test/customer-sync.spec.js
make sure that customer sync-actions are generating in right order.
this PR, make sure that these two actions `setDefaultShippingAddress` and `setDefaultBillingAddress` will be in order after adding new address, so ctp platform wont fire error complaining that address id not found.
- Tests
=> fix(sync-actions): organize customer sync actions, ex: addAdress, then setDefaultShippingAddress

packages/sync-actions/src/order-actions.js, packages/sync-actions/src/orders.js, packages/sync-actions/test/order-sync.spec.js
Adds functionality to create update actions for order's `returnInfo` and `delivery parcel`.
- add `returnInfo` update actions
- add `parcel` update actions
- write tests for both update actions
- Tests
=> feat(sync-actions): create more order update actions

packages/product-exporter/package.json
Update packages to fix security vulnerabilities, the following packages flagged the Github security warnings:
- yargs-parser
- hosted-git-info
- y18n
I updated the above packages to the recommended versions in an attempt to fix the Github security warnings.
- yargs-parser = 2.0.0
- hosted-git-info = 2.8.9
- y18n = 3.2.2
- Tests
=> Fix the security Vulnerabilities

packages/sync-actions/src/products.js, packages/sync-actions/test/product-sync-base.spec.js
For product variants, users can add a `staged` flag which only sets the `staged` projection to `current`. This adds the functionality.
- include check in `doMapActions` fn
- add test
- Tests
=> feat(products): create update actions for `staged` flag

docs/sdk/api/typescriptSdk.md, types/sdk.js
Tasks:
- add more details and explanation to the timeout and backoff properties
- add more details and explanation to the retryConfig objects and all it's properties including:
- maxRetries
- backoff
- maxDelay
- retryDelay
Add more details explanation 
This PR includes more detailed explanation of some of the most used http middleware object properties.
- Tests
=> Update Typescript Docs

.changeset/four-mangos-warn.md, packages/sync-actions/src/product-selections-actions.js, packages/sync-actions/src/product-selections.js, packages/sync-actions/test/product-selections-sync.spec.js
- Product Selections are introduced to the platform since January. We also have implemented a view in the MC to enable users to create product selection and also update them. Since the product selection were not public, the sync action for updating the product selection were generated locally in the MC code base and used for the update mutations of the GraphQL API. This PR adds product selections related sync actions to the `sync-actions` package.
=> feat(sync-actions): add product selection sync actions

docs/sdk/api/typescriptSdk.md
- comment off all the TS section from docs
- provide a link to redirect users to the new documentation
We now have a new and more lucid documentation from the docs team and hence no need for this duplicate doc of the TS SDK.
- Tests
=> Remove TS section from documentation

.changeset/gorgeous-terms-cheer.md, integration-tests/sdk/channels.it.js
I have [a fix](https://github.com/commercetools/nodejs/commit/25cb3f3cc92ce83888582eae6d98075c5f46ba02) merged into main branch to fix `regeneratorRuntime` however it was never released probably because of our new release process. So created this changeset to release the patch version of the mentioned package. 
Fix: https://jira.commercetools.com/browse/SUPPORT-17037
=> chore - release resource-deleter patch version

.changeset/six-melons-hope.md, packages/sync-actions/src/types-actions.js, packages/sync-actions/test/types-sync-enums.spec.js
Fixes: https://jira.commercetools.com/browse/SUPPORT-16999
When using the sync-actions library to sync custom types wrong update actions are generated when enum values are updated.
we check for the attribute type with a lower ‘e’ instead of an capital 'E’ as required in the CustomFieldEnumType.
Also, we don't pass fieldName when generating the action so it takes type as a fieldName which is incorrect.
=> fix(sync-actions): fix enum type actions

packages/sync-actions/src/prices-actions.js, packages/sync-actions/src/prices.js, packages/sync-actions/test/price-sync.spec.js
add support for update actions for standalone prices:
- changeValue
- setDiscountedPrice
- setCustomType
- setCustomField
- Tests
=> feat(sync-actions): add support for standalone prices

.changeset/healthy-donuts-grow.md, packages/sdk-middleware-auth/src/base-auth-flow.js
Reduce the window period the SDK should fetch a new token to accommodate for the new 1 hours token validity period.
[Jira](https://jira.commercetools.com/browse/SUPPORT-17055)
=> Reduce Token Fetch Window

.changeset/wise-timers-shake.md, packages/sync-actions/src/utils/copy-empty-array-props.js, packages/sync-actions/test/utils/copy-empty-array-props.spec.js
Refactors a little bit the way `copyEmptyArrayProps` is implemented in order to seek a better performance specially for cases with a huge amount of items in an array.
Context: We (pangolins) do a heavy use of this library in Audit Log. We were observing some customer comparisons that were taking a huge amount of time and when debugging that led us to spotting sync actions library as the one that was causing the delay.
After some investigation, we found that the library was not really performant for cases when customers with a huge amount of addresses where compared between versions. In our case it was a customer with almost 13k addresses in the old and new version.
In this PR we propose a solution by changing the implementation to remove the usage of spread operators inside a reduce in …
=> refactor(utils): improve performance of `copyEmptyArrayProps` function

packages/sync-actions/src/quote-requests-actions.js, packages/sync-actions/src/quote-requests.js, packages/sync-actions/test/quote-requests-sync.spec.js
Add sync-actions coverage for quote requests. [link to docs](https://docs.commercetools.com/api/projects/quote-requests#update-actions)
=> feat(sync-action): add support for quote requests

packages/sync-actions/src/staged-quotes-actions.js, packages/sync-actions/src/staged-quotes.js, packages/sync-actions/test/staged-quotes-sync.spec.js
Add sync-actions coverage for staged quotes. [link to docs](https://docs.commercetools.com/api/projects/staged-quotes#update-actions)
=> feat(sync-action): add support for staged quotes

.changeset/flat-phones-explain.md, packages/sync-actions/src/order-actions.js, packages/sync-actions/test/order-sync.spec.js
As in my previous PR, Audit Log does a heavy usage of sync actions for getting the diff between versions of the same entity.
For one of the events we were having some issues with how sync actions was calculating the diff for an order.
This time we have found an event that was returning an error from the sync actions library. It was related to the way we calculated the diff inside `returnInfo`.
The first commit contains a test case in which the error will show up.
The second commit contains the proposed fix.
Let me know your thoughts 🙏 
- Tests
=> fix(sync-actions/orders): adjust diff calculation of returnInfo items

.changeset/tiny-wombats-arrive.md, packages/sdk-auth/package.json, packages/sdk-auth/src/auth.js, packages/sdk-auth/test/token-provider.spec.js, yarn.lock
Remove redundant dependencies
Remove `lodash.defaultsdeep` from dependency tree
- Tests
Thanks to [@studentIvan](https://github.com/studentIvan) for the suggestions and recommended performance optimization [here](https://github.com/commercetools/nodejs/issues/1653)
=> Remove redundant dependencies

.changeset/two-timers-flash.md, packages/discount-code-importer/src/main.js
- Pass error message to the consumer. Currently in impex we only see the generic coming from the Discount Importer. So with this PR we are also pushing specific error message in the array which we show in the UI
Fix: #1832
=> fix(discount-code-importer): improve error logging

.changeset/rich-taxis-shake.md, packages/sync-actions/src/customer-actions.js, packages/sync-actions/src/customers.js, packages/sync-actions/test/customer-sync.spec.js
Generate `setAuthenticationMode` sync action.
https://docs.commercetools.com/api/history/change-types#setauthenticationmodechange
Unit tests and changeset has been added.
=> Add set authentication mode sync action

.changeset/breezy-glasses-guess.md, packages/sync-actions/src/utils/copy-empty-array-props.js, packages/sync-actions/test/product-sync-prices.spec.js
At times consumers may pass in frozen arrays. Even though this is discouraged it worked before. Syncing frozen arrays doesn't work as we copy properties from one to another. Hence we need to slice a frozen array.
=> fix: failing to sync froozen arrays for prices

.changeset/afraid-eels-sleep.md, packages/sync-actions/src/order-actions.js, packages/sync-actions/src/orders.js, packages/sync-actions/test/order-sync.spec.js
In Audit Log, we have found that the order sync actions does not correctly detect changes related to the items in a delivery.
The idea is based on the approach that we already do for `parcels` but applied to `items`. In this case is simpler as there are not add/remove actions, just a `set` action.
- Tests
=> [PANGOLIN-2857]: Support changes on delivery items (`setDeliveryItems`)

.changeset/khaki-radios-destroy.md, packages/sdk-middleware-http/src/http.js, packages/sdk-middleware-http/test/http.spec.js
Serialization of response object throws unhandled promise rejection errors
Intermittent unhandled promise rejection errors occurs due to bad object serialization.
#1858 
DEVX-180 - Jira
=> Fix issue with intermittent promise rejection error

.changeset/sharp-geckos-hear.md, packages/sync-actions/src/prices-actions.js, packages/sync-actions/test/price-sync.spec.js
This PR adds support for StandalonePrice `setPriceTiers`,
- Tests
=> feat: add missing sync action for StandalonePrice entity `setPriceTiers`

.changeset/tough-lions-flow.md, packages/sync-actions/src/prices-actions.js, packages/sync-actions/test/price-sync.spec.js
this pr fixes the typo on setPriceTiers -> setPriceTier this is the correct acction : https://docs.commercetools.com/api/projects/standalone-prices#set-price-tiers
- Tests
=> Ma fix sync set price tier

.changeset/violet-timers-act.md, packages/sync-actions/src/utils/diffpatcher.js, packages/sync-actions/test/product-sync-variants.spec.js
Audit Log has run into a few edge cases where clients set VERY long `values` on product attributes. The result is that diffing takes a long time (can be > 7-10s or more).
After running down where the delay is coming from, it appears it is due to `jsondiffpatch` uses `diff-match-patch` for long text diffing, which uses a very fine-grained diffing algorithm for long to easily identify what changed between two strings (this is actually the library originally built by google for google docs comparisions). However, we don't actually care about the specifics of what changed between two strings - we only care if the string changed at all. 
This PR adds a test in the first commit which shows the edge case (long values with a failing result b/c it should take ~5ms and it takes 5s). The second …
=> fix: handle long text values performantly

packages/product-json-to-xlsx/test/writer.spec.js, packages/sdk-middleware-http/src/http.js, packages/sdk-middleware-http/test/http.spec.js
Fix error causing SDK to crash if a promise rejection error occurs due to improper serialization of response body.
=> Fix Unhandled Promise Rejection Error

.github/workflows/release.yml
Replaces the usage of a static long-lived PAT with a short-lived (auto revoked) PAT through a GitHub Application called CT Changesets.
This is being rolled out across about 10 repositories. More detail and background on the changes can be found on internal documentation.
=> refactor(ci): to use github application for pat

.changeset/shy-onions-explode.md, packages/sync-actions/src/shipping-methods-actions.js, packages/sync-actions/test/shipping-methods.spec.js
This PR adds the action for `changeActive` to the `baseActionsList` for Shipping Methods.
- Tests
=> feat: add changeactive action and test

.changeset/curvy-seas-protect.md, packages/sync-actions/src/projects-actions.js, packages/sync-actions/test/projects-sync.spec.js
Adds missings project actions.
Some missing actions added to the `baseActionsList` in the `projects-actions.js` file.
The missing actions are `changeMyBusinessUnitStatusOnCreation`, `setMyBusinessUnitAssociateRoleOnCreation`, and `changeCustomerSearchStatus`.
- Tests
=> feat(customers): add missing search and bu actions

.changeset/seven-tools-brake.md, packages/sync-actions/src/projects-actions.js, packages/sync-actions/src/projects.js, packages/sync-actions/test/projects-sync.spec.js
Summary
Fix myBusinessUnit and customerSearch project actions.
Description
Some project actions I added recently had the wrong keys. I fixed those and split the actions into groups myBusinessUnit and customerSearch because changeMyBusinessUnitStatusOnCreation and changeCustomerSearchStatus have the same key: `status`. 
- Tests
=> fix(projects): fix myBusinessUnits and customerSearchStatus action keys

.changeset/olive-poets-impress.md, packages/sync-actions/src/products.js, packages/sync-actions/test/product-sync-base.spec.js
Map the `categoryOrderHints` actionGroup to the corresponding `actionsMapCategoryOrderHints` function.
- [test: categoryOrderHints actionGroup](https://github.com/commercetools/nodejs/commit/15652b2edb31d915c89671417acad42b524aa186)
Check how the tests are [failing](https://app.circleci.com/pipelines/github/commercetools/nodejs/4452/workflows/0c7180c8-fac8-4b27-9003-3fedd47a666c/jobs/24159?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary)
- [fix: align categoryOrderHints with the corresponding actionGroup](https://github.com/commercetools/nodejs/commit/ee7b0f2eba1031c12e6f40d4c782449957d3b548)
now tests are passing
- Tests
=> Fix product action groups category order hints

.changeset/shy-badgers-remain.md, jest.test.config.js, packages/sync-actions/package.json, packages/sync-actions/src/utils/diffpatcher.js, yarn.lock
In this PR we're getting rid of a `require` statement that (according to the code comment above it) we wanted to remove and that's also causing some troubles for consumers who have a ES modules setup.
Our codebase is using ES module which handles modules dependencies using `import/export` statements. However, we have one dependency (`jsondiffpatch`) that does not support such statements as it's bundles only with CommonJS exports. Thus, we needed to use an unwanted `require` statement to actually be able to use it in our `sync-actions` package.
My first attempt was to update the `jsondiffpatch` dependency to its latest version ([v0.6.0](https://github.com/benjamine/jsondiffpatch/releases/tag/v0.6.0)) as they have migrated to ES modules in that one. There's one caveat though with that …
=> Remove unwanted "require" usage in sync-actions package

.changeset/hungry-cats-yell.md, packages/sync-actions/src/attribute-groups-actions.js, packages/sync-actions/src/cart-discounts-actions.js, packages/sync-actions/src/category-actions.js, packages/sync-actions/src/channels-actions.js, packages/sync-actions/src/customer-actions.js, packages/sync-actions/src/customer-group-actions.js, packages/sync-actions/src/discount-codes-actions.js, packages/sync-actions/src/inventory-actions.js, packages/sync-actions/src/order-actions.js, packages/sync-actions/src/prices-actions.js, packages/sync-actions/src/product-actions.js, packages/sync-actions/src/product-discounts-actions.js, packages/sync-actions/src/product-selections-actions.js, packages/sync-actions/src/product-types-actions.js, packages/sync-actions/src/projects-actions.js, packages/sync-actions/src/quote-requests-actions.js, packages/sync-actions/src/quotes-actions.js, packages/sync-actions/src/shipping-methods-actions.js, packages/sync-actions/src/staged-quotes-actions.js, packages/sync-actions/src/state-actions.js, packages/sync-actions/src/stores-actions.js, packages/sync-actions/src/stores.js, packages/sync-actions/src/tax-categories-actions.js, packages/sync-actions/src/types-actions.js, packages/sync-actions/src/utils/common-actions.js, packages/sync-actions/src/zones-actions.js, packages/sync-actions/test/price-sync.spec.js, packages/sync-actions/test/utils/common-actions.spec.js, types/sdk.js
The import-api is committed to unset properties of a resource if the supplied request omits the specified keys.
The sync-actions currently only generate unset actions if the supplied key is present but null. This PR introduces two flags, that controls this behaviour. The default behaviour is kept the same, if this flags are not supplied.
More information can be found in the respective [SUPPORT ticket](https://commercetools.atlassian.net/browse/SUPPORT-30603?focusedCommentId=888857)
Upon approval, I will run a changeset command and include it in this PR.
This flag controls, wether an omitted property should lead to generating an updateAction:
This is how it is intended to work:
```typescript
describe('`shouldUnsetOmittedProperties`', () => {
test('if true => should generate unset actions …
```
=> feat(sync-actions): provide option to generate empty update actions for ommitted properties

.changeset/giant-wombats-relate.md, packages/csv-parser-discount-code/src/cli.js, packages/csv-parser-state/src/cli.js, packages/discount-code-exporter/src/cli.js, packages/discount-code-generator/src/cli.js, packages/inventories-exporter/src/cli.js, packages/price-exporter/src/cli.js, packages/product-json-to-csv/src/cli.js, packages/product-json-to-xlsx/src/cli.js
- https://github.com/commercetools/fe-chapter-notes/issues/490
=> chore: to replace fs.access with fs.exist

package.json, pnpm-lock.yaml
This was added in https://github.com/commercetools/nodejs/commit/a4705c19af234cccde74cb52bfff912bf380c6ba and is not needed anymore. It also right now breaks lint-staged when commmiting.
=> refactor: remove chalk resolution

README.md, docs/sdk/api/getCredentials.md, docs/sdk/api/httpUserAgent.md, docs/sdk/api/sdkAuth.md, docs/sdk/api/sdkClient.md, docs/sdk/api/sdkMiddlewareAuth.md, docs/sdk/api/sdkMiddlewareCorrelationId.md, docs/sdk/api/sdkMiddlewareHttp.md, docs/sdk/api/sdkMiddlewareLogger.md, docs/sdk/api/sdkMiddlewareQueue.md, docs/sdk/api/sdkMiddlewareUserAgent.md, packages/get-credentials/readme.md, packages/http-user-agent/README.md, packages/sdk-auth/README.md, packages/sdk-client/README.md, packages/sdk-middleware-auth/README.md, packages/sdk-middleware-correlation-id/README.md, packages/sdk-middleware-http/README.md, packages/sdk-middleware-logger/README.md, packages/sdk-middleware-queue/README.md, packages/sdk-middleware-user-agent/README.md, packages/sdk-types/README.md
These packages have been replaced by the TypeScript SDK. We should inform users stumbling upon this repository of it.
=> docs: add deprecation notice to legacy sdks

.renovaterc.json, packages/sync-actions/package.json, packages/sync-actions/src/utils/diffpatcher.js, pnpm-lock.yaml
In the major release of packages of this repository in #1930 the `jsondiffpatcher` library was bumped to v0.6.0. This version however is ESM only.
That version is also the last version with a good release note. The ESM only mode may work for Node.js environments as all supported environments support ESM but can fail in browsers and testing environments. 
As this library doesn't rely on specifics of the jsondiffpatcher library we can consider downgrading.
The proceeding of this will be discussed internally.
=> Downgrade `jsondiffpatcher` to v0.5.0 prior becoming ESM only

.changeset/warm-webs-dream.md, packages/sync-actions/src/product-actions.js, packages/sync-actions/src/products.js, packages/sync-actions/test/product-sync-base.spec.js, packages/sync-actions/test/product-sync-variants.spec.js
https://commercetools.atlassian.net/browse/PDM-236
Add Support for importing products, product drafts with product level attributes
I suggest t review commit by commit to get a more meaningful diff
=> PDM-236 Add support for product level attributes
