commercetools/nodejs

SUMMARY.md
docs/sdk/api/README.md
docs/sdk/api/createLoggerMiddleware.md
packages/commercetools-sdk-middleware-logger/README.md
packages/commercetools-sdk-middleware-logger/package.json
packages/commercetools-sdk-middleware-logger/src/index.js
packages/commercetools-sdk-middleware-logger/src/logger.js
packages/commercetools-sdk-middleware-logger/test/logger.spec.js

affects: @commercetools/sdk-middleware-logger
Add logger middleware
- Tests

feat(sdk-middleware-logger): add package for middleware-logger

---

SUMMARY.md
docs/sdk/api/README.md
docs/sdk/api/createHttpUserAgent.md
packages/commercetools-http-user-agent/README.md
packages/commercetools-http-user-agent/package.json
packages/commercetools-http-user-agent/src/create-user-agent.js
packages/commercetools-http-user-agent/src/index.js
packages/commercetools-http-user-agent/test/create-user-agent.spec.js
types/sdk.js

Extracts logic of creating a HTTP user-agent from `@commercetools/sdk-middleware-user-agent`.
Ref #1

Add standalone package for creating a proper HTTP user-agent

---

CONTRIBUTING.md

docs(contributing): add commit message example and command

---

package.json

chore(package): add command to commit following the commit template

---

package.json

Version 0.3.2 of `cz-lerna-changelog` fixes compatiblity with `lerna beta.30`.
- Tests

chore(package): update cz-lerna-changelog to version 0.3.2

---

packages/commercetools-api-request-builder/src/default-services.js
packages/commercetools-api-request-builder/test/create-request-builder.spec.js

adds the payments API to the reqest builder with minimal features
see summary
- Tests

feat(api-request-builder): add the payments service

---

lerna.json
package.json
yarn.lock

- lerna #48 
- lerna-semantic-release #52 
- eslint #49 
- validate-commit-msg #51

Upgrade deps

---

docs/sdk/api/sdkMiddlewareHttp.md
packages/sdk-client/src/client.js
packages/sdk-client/test/client.spec.js
packages/sdk-middleware-http/src/http.js
packages/sdk-middleware-http/test/http.spec.js
types/sdk.js

feat(http): add server headers to response

---

packages/api-request-builder/src/default-services.js
packages/api-request-builder/test/create-request-builder.spec.js

Resolves #128 
This PR adds a support for ShoppingLists endpoint.
- Tests

feat(apiRequestBuilder): Add a support for ShoppingLists endpoint

---

integration-tests/cli/csv-parser-price.it.js

test(integration): fix failing integration test

---

.babelrc
package.json
packages/sdk-client/src/client.js
packages/sdk-client/src/validate.js
packages/sdk-client/test/client.spec.js
yarn.lock

affects: @commercetools/sdk-client
validate the request shape and function arguments in the `exec` and `process` methods
resolves #41

feat(sdk-client): validate arguments

---

packages/api-request-builder/src/default-services.js
packages/api-request-builder/test/create-request-builder.spec.js

affects: @commercetools/api-request-builder
Fixes #138 
- Tests

feat(api-request-builder): add support for order-import

---

docs/cli/csv-parser-price.md
integration-tests/cli/csv-parser-price.it.js
packages/csv-parser-price/src/cli.js
packages/csv-parser-price/src/main.js
packages/csv-parser-price/test/main.spec.js

137 support access token

---

integration-tests/cli/expected-output/csv-parser-price.json
packages/csv-parser-price/src/main.js
packages/csv-parser-price/test/main.spec.js

affects: @commercetools/csv-parser-price
Fixes #156 
- Tests

fix(csv-parser-price): correct sku field

---

.travis/after_success.sh

build(travis): automate docs publishing after merging

---

packages/csv-parser-price/src/main.js
packages/csv-parser-price/test/main.spec.js

affects: @commercetools/csv-parser-price
Fixes #164 
- Tests

fix(csv-parser-price): add currencyCode to data

---

docs/cli/README.md
docs/cli/discount-code-generator.md

affects: @commercetools/discount-code-generator

docs(discount-codes): Write documentation for discount code generator

---

docs/sdk/api/apiRequestBuilder.md
packages/api-request-builder/src/build-query-string.js
packages/api-request-builder/src/query-projection.js
packages/api-request-builder/test/build-query-string.spec.js
packages/api-request-builder/test/query-projection.spec.js
types/sdk.js

affects: @commercetools/api-request-builder
Fixes #154 
- Tests

feat(api-request-builder): add support for price selection

---

packages/api-request-builder/src/build-query-string.js
packages/api-request-builder/src/query-page.js
packages/api-request-builder/test/build-query-string.spec.js

feat(api-request-builder): Enable zero limit in request query

---

docs/SUMMARY.md
docs/cli/discount-code-generator.md
packages/discount-code-generator/package.json
packages/discount-code-generator/readme.md
packages/discount-code-generator/src/cli.js

affects: @commercetools/discount-code-generator
fix wrong links in documentation, minor refactoring
resolves #183

fix(discount-code-generator): update documentation

---

README.md
docs/SUMMARY.md
docs/cli/README.md
docs/cli/discount-code-importer.md
packages/discount-code-importer/readme.md

Documentation for the code importer module (#171)
resolves #173

docs(discount-code-importer): Create docs

---

integration-tests/cli/csv-parser-order.it.js
packages/csv-parser-order/src/cli.js
packages/csv-parser-order/src/parsers/abstract-parser.js
packages/csv-parser-order/src/parsers/add-return-info.js
packages/csv-parser-order/src/parsers/deliveries.js
packages/csv-parser-order/src/parsers/line-item-state.js
packages/csv-parser-order/test/add-return-info.spec.js
packages/csv-parser-order/test/deliveries.spec.js

affects: @commercetools/csv-parser-order
- Tests

refactor(csv-parser-order): refactor stream implementation

---

docs/cli/discount-code-generator.md
packages/discount-code-generator/package.json
packages/discount-code-generator/src/cli.js
packages/discount-code-generator/src/utils.js
packages/discount-code-generator/test/helpers/sampleJSON.json
packages/discount-code-generator/test/utils.spec.js

affects: @commercetools/discount-code-generator
ISSUES CLOSED: #205

fix(discount-code-generator): fix cartDiscounts field

---

CONTRIBUTING.md
package.json
scripts/publish-manually

chore(scripts): add script to publish manually

---

packages/sdk-client/src/client.js
packages/sdk-client/test/client.spec.js

affects: @commercetools/sdk-client
resolves: #226

fix(sdk-client): handle user rejected promises

---

integration-tests/cli/helpers/inventories.data.js
integration-tests/cli/inventories-exporter.it.js

test(inventory-exporter): refactor integration test and helper

---

docs/cli/discount-code-importer.md
integration-tests/cli/discount-code-importer.it.js
packages/discount-code-importer/src/main.js
packages/discount-code-importer/test/main.spec.js
types/discountCodes.js

add support for access token
BREAKING CHANGE: on successful import, the returned promise does not resolve to the summary. The `summaryReport()` must be called directly if the summary is required.

240 importer token

---

packages/csv-parser-discount-code/src/main.js
packages/csv-parser-discount-code/src/utils.js
packages/csv-parser-discount-code/test/utils.spec.js

affects: @commercetools/csv-parser-discount-code
resolves #244

fix(csv-parser-discount-code): properly cast types

---

docs/SUMMARY.md
docs/cli/README.md
docs/cli/discount-code-exporter.md
packages/discount-code-exporter/readme.md

Add documentation for the discount code exporter

docs(code-exporter): add documentation

---

docs/SUMMARY.md
docs/cli/README.md
docs/cli/discount-code-exporter.md
packages/discount-code-exporter/bin/discount-code-exporter.js
packages/discount-code-exporter/package.json
packages/discount-code-exporter/readme.md
packages/discount-code-exporter/src/cli.js
packages/discount-code-exporter/src/index.js
packages/discount-code-exporter/src/main.js
packages/discount-code-exporter/test/main.spec.js
types/discountCodes.js

144 code export main

---

integration-tests/cli/discount-codes.it.js
integration-tests/package.json
packages/discount-code-exporter/src/cli.js
packages/discount-code-exporter/src/main.js
packages/discount-code-exporter/test/main.spec.js

Add integration tests for the discount code importer package
Refactor code to fix errors noticed during integration testing

Code exporter Integration test

---

docs/SUMMARY.md
docs/cli/README.md
docs/cli/discount-code-exporter.md
integration-tests/cli/discount-codes.it.js
integration-tests/package.json
packages/discount-code-exporter/bin/discount-code-exporter.js
packages/discount-code-exporter/package.json
packages/discount-code-exporter/readme.md
packages/discount-code-exporter/src/cli.js
packages/discount-code-exporter/src/index.js
packages/discount-code-exporter/src/main.js
packages/discount-code-exporter/test/main.spec.js
types/discountCodes.js

This PR adds a new module to export commercetools discount codes from the CTP
resolves #144
BREAKING CHANGE: initial release

feat(discount-code-exporter): add new module

---

package.json

chore(package): update cross-env to version 5.0.3

---

packages/sync-actions/src/product-actions.js
packages/sync-actions/src/products.js
packages/sync-actions/src/utils/find-matching-pairs.js
packages/sync-actions/test/product-sync-images.spec.js
packages/sync-actions/test/product-sync-prices.spec.js
packages/sync-actions/test/product-sync-variants.spec.js
packages/sync-actions/test/utils/find-matching-pairs.spec.js

fix(sync-actions): fix non-matching variant image update action generation

---

packages/discount-code-importer/src/main.js
packages/discount-code-importer/test/main.spec.js

affects: @commercetools/discount-code-importer
Decrease maximum batch size for simultaneous code imports
resolves #327

fix(main): decrease maximum batch size

---

packages/sync-actions/src/product-actions.js
packages/sync-actions/test/product-sync-images.spec.js

change the `changeImageLabel` update action to `setImageLabel`
resolves #322

fix(sync-actions): update image update action

---

.travis/after_success.sh
package.json
yarn.lock

Installing dependencies before releasing with npm.

chore(travis): fix release with npm install on after_success

---

.circleci/perform-release-packages.sh
.circleci/prepare-release-packages.sh

chore(release): fix env variables used

---

lerna.json
package.json

chore(build): add default commit message

---

packages/sync-actions/src/customers.js
packages/sync-actions/test/customer-sync.spec.js

Adds custom field support for customers.

Add support custom fields for customers

---

packages/get-credentials/readme.md
packages/http-user-agent/README.md
packages/sdk-client/README.md
packages/sdk-middleware-auth/README.md
packages/sdk-middleware-http/README.md
packages/sdk-middleware-logger/README.md
packages/sdk-middleware-queue/README.md
packages/sdk-middleware-user-agent/README.md
packages/sync-actions/README.md

Some links are broken. This PR replaces the wrong link with the right one.

Broken links

---

packages/api-request-builder/src/default-services.js
packages/api-request-builder/test/create-request-builder.spec.js

feat(api-request-builder): add support for api extensions

---

packages/api-request-builder/src/default-services.js
packages/api-request-builder/test/create-request-builder.spec.js

For more please refer to #447.
Closes #447

feat(api-request-builder): add password token and password reset

---

LICENSE

add MIT license file (as in the `package.json` file and Node SDK)
resolves #323

docs(license): add a license file

---

docs/SUMMARY.md
docs/cli/csv-parser-discount-code.md
docs/cli/csv-parser-orders.md
docs/cli/csv-parser-price.md
docs/cli/discount-code-exporter.md
docs/cli/discount-code-generator.md
docs/cli/discount-code-importer.md
docs/cli/inventories-exporter.md
docs/cli/price-exporter.md
docs/cli/product-exporter.md
docs/sdk/Middlewares.md
docs/sdk/api/sdkMiddlewareAuth.md

This PR adds documentation for middleware feature to add accessToken to API request header
This PR Also update links to API specification artifacts
resolves #446 
resolves #455

446 docs update

---

packages/sync-actions/src/product-types-actions.js
packages/sync-actions/test/product-types-sync-base.spec.js

fix(sync-action): setDescription -> changeDescription

---

packages/product-json-to-csv/src/main.js
packages/product-json-to-csv/src/writer.js
packages/product-json-to-csv/test/helpers/csvFileWithDelimiter.csv
packages/product-json-to-csv/test/writer.spec.js

affects: @commercetools/product-json-to-csv
PR fixes custom delimiter
resolves #529

fix(json-to-csv): fix custom delimiter

---

docs/SUMMARY.md
docs/sdk/api/README.md
docs/sdk/api/sdkMiddlewareCorrelationId.md
packages/sdk-middleware-correlation-id/README.md
packages/sdk-middleware-correlation-id/package.json
packages/sdk-middleware-correlation-id/src/correlation-id.js
packages/sdk-middleware-correlation-id/src/index.js
packages/sdk-middleware-correlation-id/test/correlation-id.spec.js
rollup.config.js
types/sdk.js
yarn.lock

Closes #551 
This adds the correlation id middleware discussed in the issue. It's not necessarily meant to be perfect yet. However, I felt some code would help to continue the discussion. This in my opinion would be the middleware in its simplest form.

Add `sdk-client/middleware-correlation-id`

---

packages/product-json-to-csv/src/main.js

Change code to use promises instead of async/await.
resolves #560

fix(product-json-to-csv): use promises instead of async/await

---

.circleci/config.yml
package.json

closes #648
closes #649
closes #650

chore(deps): update deps

---

.circleci/config.yml
package.json

Dependencies update
- update circleci/node:6 docker digest to ba7d75
- update circleci/node:8 docker digest to 73b4f6
- update dependency eslint-plugin-jest from v21.17.0 to v21.18.0
closes #675 
closes #676 
closes #677

chore(deps): update dependencies

---

.circleci/config.yml

Dependencies update
- update circleci/node:6 docker digest to 172485
- update circleci/node:8 docker digest to f1063d
Closes #691 
Closes #692

chore(deps): dependencies update of circleci

---

.circleci/config.yml

Update dependencies
Update dependencies of circle/node
- circleci/node:6 docker digest to 09fa58
- circleci/node:8 docker digest to 339b91
Closes #696 
Closes #697

chore(deps): update dependencies of circleci node

---

CONTRIBUTING.md
TODOS.md

Update contribution guidelines 
- Contribution guidelines update on how to carry out Integration Test.
Closes the PR [here](https://github.com/commercetools/nodejs-tasks-board/issues/13)

docs(contributing.md): update docs on integration test

---

.circleci/config.yml

Update dependencies
- Update circleci/node:6 docker digest to 830d79
- Update circleci/node:8 docker digest to dc6fc7
Closes #714 
Closes #715

chore(deps): update dependencies of circleci/node

---

packages/product-json-to-csv/package.json

fix(product-json-to-csv): add a missing dependency

---

TODOS.md
integration-tests/cli/__snapshots__/inventories-exporter.it.js.snap
integration-tests/cli/inventories-exporter.it.js
packages/inventories-exporter/src/main.js
packages/inventories-exporter/test/__snapshots__/main.spec.js.snap
packages/inventories-exporter/test/main.spec.js
types/inventory.js

https://jira.commercetools.com/browse/SUPPORT-3718
PR adds `createdAt` and `lastModifiedAt` to inventories-exporter when doing CSV export.
- Tests
resolves #724

feat(inventories-exporter): include createdAt and lastModifiedAt

---

packages/product-json-to-csv/src/main.js
packages/product-json-to-csv/test/main.spec.js

fix(product-json-to-csv): fix caching channels

---

TODOS.md
packages/product-json-to-csv/src/writer.js
packages/product-json-to-csv/test/__snapshots__/writer.spec.js.snap
packages/product-json-to-csv/test/writer.spec.js

Fixes #729 
We should check whether we have any streams (saving products) and if not, we can zip an empty folder right away.
- Tests

fix(product-json-to-csv): fix exporting zero products

---

package.json
packages/sdk-middleware-auth/package.json
packages/sdk-middleware-http/package.json
yarn.lock

resolves #805
resolves #806
resolves #807

chore: update deps

---

.flowconfig
docs/cli/product-json-to-csv.md
docs/cli/product-json-to-xlsx.md
integration-tests/cli/__snapshots__/product-json-to-xlsx.it.js.snap
packages/product-json-to-xlsx/src/cli.js
packages/product-json-to-xlsx/test/main.spec.js

Fixes #834 
Note: This feature is tested already in `product-json-to-csv`

fix(product-json-to-xlsx): add missing CLI parameter

---

integration-tests/sdk/auth.it.js
packages/sdk-middleware-auth/src/build-requests.js

PR encodes user email and password which the platform requires. More reading in these two threads ([1](https://jira.commercetools.com/browse/SUPPORT-4005) and [2](https://jira.commercetools.com/browse/CTP-1652)).
- Tests
resolves #839

fix(auth): encode username and password for password flow

---

.circleci/config.yml
yarn.lock

Fixes memory consumption error

chore(ci): use only 10 workers for linting

---

packages/sdk-client/src/client.js
packages/sdk-client/test/client.spec.js

Fixes #890
When the last page is empty, we do not call a `fn` with empty array.
- Tests

fix(sdk-client): do not call fn on last empty page

---

packages/product-json-to-csv/src/map-product-data.js

This PR is just a small fix of an outdated comment.

fix(product-json-to-csv): fix comment

---

lerna.json

Since we do not check in these files in git we should also not read/write them in the first place.

chore(lerna): update bootstrap command

---

README.md
docs/cli/README.md
packages/category-exporter/readme.md
yarn.lock

affects: @commercetools/category-exporter
category-exporter readme
Add documentation for category-exporter
Closes #902

fix(docs): add category-exporter docs

---

TODOS.md
jest-runner-eslint.config.js
packages/csv-parser-price/test/helpers/high-precision-price.csv
packages/csv-parser-price/test/main.spec.js

Test for mapping `highPrecision` Money type

test(csv-parser-price): add test for parsing high precission money type

---

integration-tests/cli/__snapshots__/category-exporter.it.js.snap
integration-tests/cli/__snapshots__/csv-parser-price.it.js.snap
integration-tests/cli/__snapshots__/custom-objects-export.it.js.snap
integration-tests/cli/__snapshots__/customer-groups-export.it.js.snap
integration-tests/cli/__snapshots__/inventories-exporter.it.js.snap
integration-tests/cli/__snapshots__/price-export.it.js.snap
integration-tests/cli/__snapshots__/product-export.it.js.snap
integration-tests/cli/__snapshots__/product-json-to-csv.it.js.snap
integration-tests/cli/__snapshots__/product-json-to-xlsx.it.js.snap
packages/category-exporter/package.json
packages/csv-parser-discount-code/package.json
packages/csv-parser-discount-code/src/cli.js
packages/csv-parser-orders/package.json
packages/csv-parser-price/package.json
packages/csv-parser-price/src/cli.js
packages/csv-parser-state/package.json
packages/custom-objects-exporter/package.json
packages/customer-groups-exporter/package.json
packages/discount-code-exporter/package.json
packages/discount-code-generator/package.json
packages/inventories-exporter/package.json
packages/price-exporter/package.json
packages/product-exporter/package.json
packages/product-json-to-csv/package.json
packages/product-json-to-xlsx/package.json

This PR adds the `cli` keyword to packages used by IMPEX to enable automation of the "CLI Overview" page on the docs site. See DOCS-44 for more information.
It also fixes a few grammar issues in the descriptions, since those are getting pulled in too ;)
I'm really not sure what kinds of testing this will need? :)
- Tests
- [ / ] Documentation

chore: add keyword for automation

---

README.md

docs: update readme with support link

---

packages/api-request-builder/package.json
packages/http-user-agent/package.json
packages/sdk-auth/package.json
packages/sdk-client/package.json
packages/sdk-middleware-auth/package.json
packages/sdk-middleware-correlation-id/package.json
packages/sdk-middleware-http/package.json
packages/sdk-middleware-logger/package.json
packages/sdk-middleware-queue/package.json
packages/sdk-middleware-user-agent/package.json
packages/sync-actions/package.json
rollup.config.js

This pull request attempts to simplify the application by:
1. Using `npm_lifecycle_event` over an custom env variable
2. Apply plugins conditionally and just filtering them out again

refactor(rollup): to use `npm_lifecycle_event`

---

TODOS.md
packages/api-request-builder/src/build-query-string.js
packages/api-request-builder/src/create-service.js
packages/api-request-builder/src/default-params.js
packages/api-request-builder/src/order-edit-apply.js
packages/api-request-builder/test/create-service.spec.js
types/sdk.js

After working together on this.

feat: add applyOrderEditTo method

---

packages/inventories-exporter/test/main.spec.js
packages/product-json-to-csv/src/main.js
packages/product-json-to-csv/test/main.spec.js
packages/product-json-to-xlsx/test/main.spec.js
yarn.lock

We were only fetching the first 20 results when resolving references here. PR solves this by iterating over each page with the handy `client.process` method. 
An alternative solution would be to fetch the maximum 500 results in one call but then we'd obviously just move the problem into the future.
- Tests
resolves #1388

fix(product-json-to-*): fetch all references

---

.flowconfig
.vscode/settings.json
husky.config.js
package.json
packages/discount-code-exporter/src/main.js
packages/product-json-to-xlsx/src/product-excel.js
rollup.config.js
yarn.lock

Extracted changes/fixes noticed in #1393 
Also, updated flow to latest version `0.107`

chore: fix flow setup

---

TODOS.md
package.json

I received these changes locally after running `yarn release` 🤷‍♂ 
I'm not entirely sure if we should keep this.
feel free to just close the PR if it is irrelevant, but I'd like to hear what is going on here

chore(package.json): deps installed

---

packages/sync-actions/src/stores-actions.js
packages/sync-actions/test/stores-sync.spec.js
yarn.lock

this PR adds support for `setLanguages` as an update action for stores. 
the action is available in graphql (found it in impex graphiql playground) but is not yet in the documentation so it should probably be added there too.
https://docs.commercetools.com/http-api-projects-stores#update-actions

feat(sync-actions): add setLanguages update action to stores

---

packages/typescript-sdk/src/generated/base/requests-utils.ts
yarn.lock

fix(ts-sdk): handling of undefined parameter

---

README.md

docs(readme): add product-json-to-xlsx in readMe under CLI tools

---

packages/typescript-sdk/src/generated/client/api-root.ts

fix(ts-sdk) fix path issue

---

integration-tests/cli/product-json-to-csv.it.js
packages/product-json-to-csv/src/map-product-data.js
packages/product-json-to-csv/test/map-product-data.spec.js

fix(product-json-to-csv): replace the @ with space before from the customer group

---

packages/typescript-sdk/package.json

fix(ts-sdk) fix version

---

packages/typescript-sdk/src/generated/index.ts
packages/typescript-sdk/src/generated/shared/utils/common-types.ts
packages/typescript-sdk/src/generated/shared/utils/middleware.ts
packages/typescript-sdk/src/generated/shared/utils/requests-utils.ts
packages/typescript-sdk/src/generated/shared/utils/uri-utils.ts

Added new middleware format to the sdk.
- Tests

add middlewares to current sdk

---

packages/product-json-to-csv/src/map-product-data.js
types/product.js

Adding productTypeKey column while exporting the products.
Fixes: #1480

feat(product-exporter): add productTypeKey column while exporting

---

.gitignore
integration-tests/cli/__snapshots__/category-exporter.it.js.snap
integration-tests/cli/__snapshots__/csv-parser-price.it.js.snap
integration-tests/cli/__snapshots__/custom-objects-export.it.js.snap
integration-tests/cli/__snapshots__/customer-groups-export.it.js.snap
integration-tests/cli/__snapshots__/inventories-exporter.it.js.snap
integration-tests/cli/__snapshots__/personal-data-erasure.it.js.snap
integration-tests/cli/__snapshots__/price-export.it.js.snap
integration-tests/cli/__snapshots__/resource-deleter.it.js.snap
packages/sdk-middleware-auth/test/client-crendentials-flow.spec.js

Updating snapshots and fixing a failing unit test for the middleware-auth package.

fix(middleware-auth): tests

---

.github/pull_request_template.md
CONTRIBUTING.md

Small PR to update the contribution guidelines and hopefully make it easier to navigate our workflow.

chore: update pr guidelines

---

docs/sdk/api/apiRequestBuilder.md

additions to api-request-builder documentation
display API endpoints, services and features in docs

docs(api-request-builder): documentation improvements

---

packages/sync-actions/src/utils/copy-empty-array-props.js
packages/sync-actions/test/utils/copy-empty-array-props.spec.js

- caused by https://github.com/commercetools/nodejs/pull/1525

Adnasa null check copy array props

---

packages/sdk-middleware-http/src/http.js
packages/sdk-middleware-http/test/http.spec.js

Fixes the broken linting on CircleCI
- Tests

small linter fixes

---

packages/sync-actions/src/product-actions.js
packages/sync-actions/src/products.js
packages/sync-actions/test/product-sync-prices.spec.js

Add enableDiscounted option to product
This PR is resolving this issue [1617](https://github.com/commercetools/nodejs/issues/1617)

feat(sync-actions): add enableDiscounted option to product

---

book.json

1634 Github Pages: add ip anonymization to the ga

---

docs/sdk/README.md

Clarificiation about the usage of the queue middleware

docs(queue): clarify usage of queue middleware

---

packages/resource-deleter/src/main.js

The queue middleware was not working in the resource deleter
ref : https://github.com/commercetools/nodejs/pull/1676
- Tests

fix(resource-deleter): re organize http middleware

---

packages/sync-actions/src/customers.js
packages/sync-actions/src/utils/copy-empty-array-props.js
packages/sync-actions/test/customer-sync.spec.js
packages/sync-actions/test/utils/copy-empty-array-props.spec.js

fix sync customer error
same issue like this https://github.com/commercetools/nodejs/pull/1525
Resolve #1602 
- Tests

fix(sync-actions): fix customer error for Cannot read property '0' of undefined

---

package.json
yarn.lock

Closes  https://github.com/commercetools/nodejs/pull/1689
Test to see if Cirlce CI will run a test job again this PR
Raise a test PR to see if Circle CI will open a test workflow/job on the PR
- Tests

Test Circle Ci

---

docs/sdk/api/sdkMiddlewareHttp.md
yarn.lock

- Add information for `abortController | getAbortController`
- Add usage examples for abortController and getAbortController
- Add a bit of context of their main differences
Expand on the already existing documentation on `abortController`, add usage examples and point out the difference between `abortController` and `getAbortController`
- Tests

Documentation - SDK Middleware Http

---

packages/personal-data-erasure/src/main.js

fix(personal-data-erasure): remove cart also while deleting all customer data

---

docs/sdk/api/typescriptSdk.md

Documentation
This add usage documentation of the [@commercetools/sdk-client-v2](https://www.npmjs.com/package/@commercetools/sdk-client-v2) package
- Tests

TypeScript Client Usage Documentation

---

integration-tests/cli/personal-data-erasure.it.js
integration-tests/sdk/auth-middleware.it.js
integration-tests/sdk/auth.it.js
packages/sdk-auth/src/tokenProvider.js
packages/sdk-auth/test/token-provider.spec.js
packages/sdk-middleware-auth/package.json
packages/sdk-middleware-auth/src/anonymous-session-flow.js
packages/sdk-middleware-auth/src/base-auth-flow.js
packages/sdk-middleware-auth/src/client-credentials-flow.js
packages/sdk-middleware-auth/src/password-flow.js
packages/sdk-middleware-auth/src/refresh-token-flow.js
packages/sdk-middleware-auth/test/base-auth-flow.spec.js
types/sdk.js
yarn.lock

Add timeout functionality to `sdk-middleware-auth` to timeout process if request exceeds a specified time.
- Tests

Add Request Timeout for `sdk-middleware-auth`

---

docs/sdk/api/sdkMiddlewareAuth.md
packages/sdk-middleware-auth/README.md
packages/sdk-middleware-http/package.json

Update Repository doc and Package version
- Tests

Update Repository Doc and Package version

---

packages/sdk-middleware-auth/src/base-auth-flow.js
packages/sdk-middleware-auth/test/base-auth-flow.spec.js
types/sdk.js

Project suspension
Suspend all activity once a project is suspended on the commerctools platform.
- Tests

Project Suspension with Retries

---

.changeset/six-lizards-compare.md

Release lastest `sdk-middleware-auth` package

Release Latest sdk-middleware-auth

---

.changeset/little-squids-build.md
packages/sync-actions/src/product-actions.js
packages/sync-actions/src/products.js
packages/sync-actions/test/product-sync-base.spec.js
packages/sync-actions/test/product-sync-variants.spec.js

Generate setPriceMode sync action.
https://docs.commercetools.com/api/projects/products#set-pricemode
Unit tests has been added.

feat(sync-actions): add setPriceMode sync action

---

.changeset/lazy-shoes-join.md
packages/sdk-middleware-http/src/http.js
yarn.lock

Fix request to allow application/graphql content-type 

---

packages/sync-actions/src/quotes-actions.js
packages/sync-actions/src/quotes.js
packages/sync-actions/test/quotes-sync.spec.js

Quotes sync action coverage. [link to docs](https://docs.commercetools.com/api/projects/quotes#update-actions)

feat(sync-actions): add support for quotes

---

.changeset/late-parents-grab.md

Adding changeset for releasing quote requests and staged quotes
Running yarn changeset for the sync-actions

feat(sync-actions): adding quote and staged quotes to changeset release

---

.changeset/thick-phones-attack.md
packages/sdk-middleware-http/src/http.js

Fix issues with file uploads when using the `@commercetools/sdk-middleware-http` pakcage.
- Tests

Fix issues with file uploads when using the `@commercetools/sdk-middleware-http` pakcage.

---

.changeset/healthy-glasses-prove.md
packages/sync-actions/src/shipping-methods.js
packages/sync-actions/test/shipping-methods.spec.js

This PR adds custom fields to Shipping Method sync actions

feat: to add custom fields to shipping method

---

.flowconfig
packages/sync-actions/src/shipping-methods-actions.js
packages/sync-actions/test/shipping-methods.spec.js
yarn.lock

This PR adds the action for `setLocalizedName` to the `baseActionsList` for Shipping Methods.
- Tests

feat: add localizedName action to shipping methods

---

.changeset/rich-taxis-shake.md

ci: changeset

---

.changeset/rich-taxis-shake.md
packages/sync-actions/src/types-actions.js
packages/sync-actions/test/types-sync-enums.spec.js

BMU-401 Fix type sync order enums

---

.changeset/rich-taxis-shake.md
packages/sync-actions/src/types-actions.js
packages/sync-actions/test/types-sync-fields.spec.js

BMU-401 fix(sync-actions): fix type sync-actions errors

---

.changeset/rich-taxis-shake.md
packages/sync-actions/src/types-actions.js
packages/sync-actions/test/types-sync-enums.spec.js
packages/sync-actions/test/types-sync-fields.spec.js

- support the following actions `changeInputHint`, `changeEnumValueLabel`, `changeLocalizedEnumValueLabel`
- Tests

BMU-401 feat(sync-actions): type entity, support new actions

---

.changeset/little-cars-obey.md

release(product-json-to-xlsx): minor version bump

---

.changeset/five-jeans-perform.md
.changeset/giant-socks-provide.md
packages/sync-actions/src/prices-actions.js
packages/sync-actions/test/price-sync.spec.js

setPriceTier need to be fixed to setPriceTiers -> documentation and schema were not in sync, this pr was confirmed by BE https://commercetools.slack.com/archives/G0173BJV97Y/p1688542895326179
- Tests

fix: fix typo documentation will be updated

---

.changeset/violet-colts-beam.md

Release the fix for unhandled Promise rejection error

Release the fix for unhandled Promise rejection error

---

docs/cli/product-exporter.md

feat(docs): add FAQ section for product-exporter - SUPPORT-27483

---

package.json
packages/personal-data-erasure/package.json
yarn.lock

Update `set-value` transitive dependency
[SUPPORT-27623](https://commercetools.atlassian.net/browse/SUPPORT-27623)
[SUPPORT-27623]: https://commercetools.atlassian.net/browse/SUPPORT-27623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Chore] Update set-value dependency

---

.changeset/nine-peaches-explain.md
packages/sync-actions/src/projects-actions.js
packages/sync-actions/test/projects-sync.spec.js

Adding business unit search status actions

[Sync-actions]: adding business unit search status actions

---

.github/workflows/docs.yml
package.json
packages/product-exporter/package.json
pnpm-lock.yaml

Rename workflow for documentation generation

---

.changeset/large-zebras-fix.md
.renovaterc.json
packages/sync-actions/package.json

v0.6.2 appears to also have the issue.

Downgrade `jsondiffpatch` to 0.6.0
